Fixing `location_metadata.py` SQL syntax error (Recidiviz/recidiviz-data#21662)
## Description of the change

Loaded to sandbox
`recidiviz-stagin.dan_deploy_reference_views.us_ix_location_metadata_materialized`

```python
>  google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/recidiviz-staging/datasets/deploy_8bc8a2_reference_views/tables?prettyPrint=false: Syntax error: Expected end of input but got keyword UNION at [5:1]
>
>  The above exception was the direct cause of the following exception:
>
>  Traceback (most recent call last):
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 405, in process_fn
>      return _create_or_update_view_and_materialize_if_necessary(
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 485, in _create_or_update_view_and_materialize_if_necessary
>      updated_view = bq_client.create_or_update_view(view, might_exist=might_exist)
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/big_query_client.py", line 946, in create_or_update_view
>      raise ValueError(
>  ValueError: Cannot update view query for [deploy_8bc8a2_reference_views.location_metadata]
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 99507d99cf27a8d1f27198ae05bbf1278dbed5d8