[Justice Counts] Pin traitlets version (Recidiviz/recidiviz-data#24266)
## Description of the change

Today when attempting to run `jupyter notebook` from
`recidiviz-research`, I got the following error. Uninstalling the
`traitlets` library and re-installing version 5.9.0 fixed the error. See
[thread](https://recidiviz.slack.com/archives/CJDCVR2AY/p1695834530847029)
```
Traceback (most recent call last):
  File "/Users/michelleorden/.local/share/virtualenvs/recidiviz-data-LblS7iSE/lib/python3.9/site-packages/notebook/traittypes.py", line 235, in _resolve_classes
    klass = self._resolve_string(klass)
  File "/Users/michelleorden/.local/share/virtualenvs/recidiviz-data-LblS7iSE/lib/python3.9/site-packages/traitlets/traitlets.py", line 2009, in _resolve_string
    return import_item(string)
  File "/Users/michelleorden/.local/share/virtualenvs/recidiviz-data-LblS7iSE/lib/python3.9/site-packages/traitlets/utils/importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'jupyter_server.contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/michelleorden/.local/share/virtualenvs/recidiviz-data-LblS7iSE/bin/jupyter-notebook", line 8, in <module>
    sys.exit(main())
  File "/Users/michelleorden/.local/share/virtualenvs/recidiviz-data-LblS7iSE/lib/python3.9/site-packages/jupyter_core/application.py", line 285, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/Users/michelleorden/.local/share/virtualenvs/recidiviz-data-LblS7iSE/lib/python3.9/site-packages/traitlets/config/application.py", line 1044, in launch_instance
    app = cls.instance(**kwargs)
  File "/Users/michelleorden/.local/share/virtualenvs/recidiviz-data-LblS7iSE/lib/python3.9/site-packages/traitlets/config/configurable.py", line 555, in instance
    inst = cls(*args, **kwargs)
  File "/Users/michelleorden/.local/share/virtualenvs/recidiviz-data-LblS7iSE/lib/python3.9/site-packages/traitlets/traitlets.py", line 1295, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/Users/michelleorden/.local/share/virtualenvs/recidiviz-data-LblS7iSE/lib/python3.9/site-packages/traitlets/traitlets.py", line 1338, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "/Users/michelleorden/.local/share/virtualenvs/recidiviz-data-LblS7iSE/lib/python3.9/site-packages/traitlets/traitlets.py", line 1314, in setup_instance
    init(self)
  File "/Users/michelleorden/.local/share/virtualenvs/recidiviz-data-LblS7iSE/lib/python3.9/site-packages/notebook/traittypes.py", line 226, in instance_init
    self._resolve_classes()
  File "/Users/michelleorden/.local/share/virtualenvs/recidiviz-data-LblS7iSE/lib/python3.9/site-packages/notebook/traittypes.py", line 238, in _resolve_classes
    warn(f"{klass} is not importable. Is it installed?", ImportWarning)
TypeError: warn() missing 1 required keyword-only argument: 'stacklevel'
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

---------

Co-authored-by: Michelle Orden <michelleorden@michelles-mbp.lan>
Co-authored-by: Helper Bot <helperbot@recidiviz.org>
GitOrigin-RevId: 321a1f4a51a72b1af0aa3253f7cdaef80ad56869