[Dataflow] Output better error when there is no StatePerson for a given person_id referenced by other input tables (Recidiviz/recidiviz-data#27066)
## Description of the change

We hit this error:
```
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-0/lib/python3.11/site-packages/recidiviz/pipelines/utils/beam_utils/person_utils.py", line 80, in process
    person = one(list(hydrated_required_entities[StatePerson.__name__]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-0/lib/python3.11/site-packages/more_itertools/more.py", line 554, in one
    raise (
ValueError: too few items in iterable (expected 1) [while running 'Build the person_metadata dictionary-ptransform-103']
```
.. which has to do with some pipeline inputs referencing a person_id
that isn't in the `StatePerson` table. This is hard to debug without
more info, so this PR catches the error and rethrows with a more useful
message.

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

See Slack thread here:
https://recidiviz.slack.com/archives/C03NQCDSUQ2/p1706116820058459

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 143e3ede547f5808aab86b7e395aa26fb8034204