[Bugfix] Include big_query/config YAML files in dataflow package data (Recidiviz/recidiviz-data#68770)
## Description of the change

Adds YAML files in `big_query.config` to dataflow flex template to fix
bug in Recidiviz/recidiviz-data#67084.

Sandbox pipelines were failing with the error:
```
File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-0/lib/python3.11/site-packages/recidiviz/pipelines/utils/beam_utils/clear_bq_table.py", line 22, in <module>
    from recidiviz.big_query.big_query_client import BigQueryClientImpl
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-0/lib/python3.11/site-packages/recidiviz/big_query/big_query_client.py", line 76, in <module>
    from recidiviz.big_query.row_access_policy_query_builder import (
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-0/lib/python3.11/site-packages/recidiviz/big_query/row_access_policy_query_builder.py", line 43, in <module>
    ] = _load_restricted_access_state_code_to_access_group()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-0/lib/python3.11/site-packages/recidiviz/big_query/row_access_policy_query_builder.py", line 37, in _load_restricted_access_state_code_to_access_group
    raw = YAMLDict.from_path(_RESTRICTED_ACCESS_YAML_PATH).raw_yaml
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/apache/beam-venv/beam-venv-worker-sdk-0-0/lib/python3.11/site-packages/recidiviz/utils/yaml_dict.py", line 56, in from_path
    with open(yaml_path, encoding="utf-8") as yaml_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/apache/beam-venv/beam-venv-worker-sdk-0-0/lib/python3.11/site-packages/recidiviz/big_query/config/restricted_access_state_groups.yaml'
```

Root cause was that package_data in dataflow_flex_setup.py didn't
include recidiviz.big_query.config YAML files.

See slack
[thread](https://recidiviz.slack.com/archives/CJDCVR2AY/p1774970648082419)
for more context.

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### ⚠️ Changing an opportunity record?
Please [consult this
document](https://www.notion.so/recidiviz/How-to-make-a-change-to-the-Opportunity-Record-1d67889f4d19807f8109f9f2f007dde3)
first to see if additional changes might be required in the admin panel
or a Zod schema. You can confirm with Polaris if unsure.

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: c3fc3349d6a35c92f2489dff47c33f8298a4e539