[deploy] Verify we are only modifying intended files when cutting looker release branch (Recidiviz/recidiviz-data#48626)
## Description of the change

something went amiss when cutting the most recent [release
branch](https://github.com/Recidiviz/looker/commit/e3d336eee10d5ef353cfec565aea39bd85b037cc#diff-9de434dc7068530e0020827e985222a99c83d6849d3eccbcf55e381d438de363)
and a bunch of files were deleted

this adds a check that we are only modifying the files we expect in the
way we are expecting before committing any changes otherwise fails like
```
ERROR: Unexpected changes detected when cutting Recidiviz/looker release branch:
D	dashboards/supervisor_homepage/supervisor_homepage_outcomes_module_usage_single_state.dashboard.lookml
D	views/validation_views/session_supervision_starts_to_dataflow_disaggregated.view.lkml
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 40e8d63bfab98c89a2af7c2dc16fe8458671cc84