[JII] Bypass Twilio validator for tests if Recidiviz user (Recidiviz/recidiviz-data#36035)
## Description of the change

This PR ensures that we check the user is a Recidiviz user if the
request to a webhook has `IsTest=true`. This also allows us to bypass
the Twilio validator in test cases, while maininting some "validation"
step.

Discovered this was necessary when using a local script and the
`requests` library to make a POST request and I encountered this
exception

```
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 915, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/flask/app.py", line 1291, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/recidiviz/case_triage/jii/jii_texts_routes.py", line 71, in validate_request
    validate_request_helper(
  File "/app/recidiviz/case_triage/helpers.py", line 77, in validate_request_helper
    signature = request.headers["X-Twilio-Signature"]
                ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/werkzeug/datastructures/headers.py", line 628, in __getitem__
    return self._get_key(key)
           ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/werkzeug/datastructures/headers.py", line 639, in _get_key
    return self.environ[f"HTTP_{key}"]  # type: ignore[no-any-return]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'HTTP_X_TWILIO_SIGNATURE'
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 2fd70fcb5169afe939e696967870d0bde26a566b