[US_ND] Correct Tbl_NcicCodes raw data config  (Recidiviz/recidiviz-data#18672)
## Description of the change

The raw data table that ND sent to us had a column labeled `DESC`, which
caused problems in ingest. I manually renamed the column `DESCRIPTION`
and reuploaded the raw data to prod and staging, and am reconfiguring
the raw data yaml here. Uploading this to a test bucket and importing to
a BQ sandbox worked fine, as did running the `_latest` query on the
updated raw data.

The problem was that the `_latest` view had keyword `DESC` in its
`SELECT` statement, referencing the column `DESC`, which was throwing a
syntax error in BQ. In future cases where the raw data column name
cannot be updated manually (like if this file were a part of an
automated transfer instead of a one-off) aliasing the dataset in the
`_latest` view would also solve this problem.

This is in response to the following error during staging deploy on the
day that the original raw data yaml (with `DESC` column) was merged into
main.

```
>  ERROR:root:Error creating or updating view [BigQueryAddress(dataset_id='deploy_ee9230_us_nd_raw_data_up_to_date_views_secondary', table_id='recidiviz_docstars_nciccodes_latest')]
>  Traceback (most recent call last):
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/big_query/big_query_client.py", line 923, in create_or_update_view
>      return self.client.update_table(bq_view, ["view_query", "description"])
>    File "/Users/phenggeler/.local/share/virtualenvs/recidiviz-data-CTYEKNH4/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 1305, in update_table
>      api_response = self._call_api(
>    File "/Users/phenggeler/.local/share/virtualenvs/recidiviz-data-CTYEKNH4/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
>      return call()
>    File "/Users/phenggeler/.local/share/virtualenvs/recidiviz-data-CTYEKNH4/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
>      return retry_target(
>    File "/Users/phenggeler/.local/share/virtualenvs/recidiviz-data-CTYEKNH4/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
>      return target()
>    File "/Users/phenggeler/.local/share/virtualenvs/recidiviz-data-CTYEKNH4/lib/python3.9/site-packages/google/cloud/_http.py", line 484, in api_request
>      raise exceptions.from_http_response(response)
>  google.api_core.exceptions.NotFound: 404 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/recidiviz-staging/datasets/deploy_ee9230_us_nd_raw_data_up_to_date_views_secondary/tables/recidiviz_docstars_nciccodes_latest?prettyPrint=false: Not found: Table recidiviz-staging:deploy_ee9230_us_nd_raw_data_up_to_date_views_secondary.recidiviz_docstars_nciccodes_latest
>
>  During handling of the above exception, another exception occurred:
>
>  Traceback (most recent call last):
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 463, in process_fn
>      return _create_or_update_view_and_materialize_if_necessary(
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 533, in _create_or_update_view_and_materialize_if_necessary
>      updated_view = bq_client.create_or_update_view(view)
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/big_query/big_query_client.py", line 929, in create_or_update_view
>      return self.client.create_table(bq_view)
>    File "/Users/phenggeler/.local/share/virtualenvs/recidiviz-data-CTYEKNH4/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 748, in create_table
>      api_response = self._call_api(
>    File "/Users/phenggeler/.local/share/virtualenvs/recidiviz-data-CTYEKNH4/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
>      return call()
>    File "/Users/phenggeler/.local/share/virtualenvs/recidiviz-data-CTYEKNH4/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
>      return retry_target(
>    File "/Users/phenggeler/.local/share/virtualenvs/recidiviz-data-CTYEKNH4/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
>      return target()
>    File "/Users/phenggeler/.local/share/virtualenvs/recidiviz-data-CTYEKNH4/lib/python3.9/site-packages/google/cloud/_http.py", line 484, in api_request
>      raise exceptions.from_http_response(response)
>  google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/recidiviz-staging/datasets/deploy_ee9230_us_nd_raw_data_up_to_date_views_secondary/tables?prettyPrint=false: Syntax error: Expected end of input but got keyword DESC at [10:29]
>
>  The above exception was the direct cause of the following exception:
>
>  Traceback (most recent call last):
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/tools/utils/script_helpers.py", line 61, in interactive_prompt_retry_on_exception
>      x = fn()
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/tools/deploy/deploy_views.py", line 162, in <lambda>
>      fn=lambda: deploy_views(
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/tools/deploy/deploy_views.py", line 146, in deploy_views
>      create_managed_dataset_and_deploy_views_for_view_builders(
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 255, in create_managed_dataset_and_deploy_views_for_view_builders
>      raise e
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 245, in create_managed_dataset_and_deploy_views_for_view_builders
>      _create_managed_dataset_and_deploy_views(
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 469, in _create_managed_dataset_and_deploy_views
>      results = dag_walker.process_dag(
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/big_query/big_query_view_dag_walker.py", line 498, in process_dag
>      raise e
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/big_query/big_query_view_dag_walker.py", line 490, in process_dag
>      execution_sec, view_result = future.result()
>    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
>      return self.__get_result()
>    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
>      raise self._exception
>    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>      result = self.fn(*self.args, **self.kwargs)
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/utils/trace.py", line 63, in _wrapper
>      res = span(func)(*args, **kwargs)
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/utils/trace.py", line 96, in run_inside_new_span
>      return func(*args, **kwargs)
>    File "/Users/phenggeler/.local/share/virtualenvs/recidiviz-data-CTYEKNH4/lib/python3.9/site-packages/opencensus/common/runtime_context/__init__.py", line 85, in call_with_current_context
>      return func(*args, **kwargs)
>    File "/Users/phenggeler/workspace/recidiviz-data-deployment/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 467, in process_fn
>      raise ValueError(f"Error creating or updating view [{v.address}]") from e
>  ValueError: Error creating or updating view [BigQueryAddress(dataset_id='deploy_ee9230_us_nd_raw_data_up_to_date_views_secondary', table_id='recidiviz_docstars_nciccodes_latest')]
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Reverted view change that references this raw data: Recidiviz/recidiviz-data#18648
Reverted original raw data config Recidiviz/recidiviz-data#18656

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no
"Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: a0ebd9bfa9e85954c499349af0a7fb4d922a0106