Use state code for normalization dataset (Recidiviz/recidiviz-data#33863)
## Description of the change
Getting this error with the full_sandbox_pipeline.sh script:
Proceeding with command.
[2024-10-01 16:00:32] Running: python -m
recidiviz.tools.calculator.run_sandbox_calculation_pipeline --pipeline
incarceration_metrics --type metrics --project recidiviz-staging
--output_sandbox_prefix zaaron_td_with_401 --state_code US_ME
--input_dataset_overrides_json {"normalized_state":
"zaaron_td_with_401_us_me_normalized_state"} --metric_types
INCARCERATION_ADMISSION INCARCERATION_COMMITMENT_FROM_SUPERVISION
INCARCERATION_RELEASE
> Have you already created a sandbox dataflow dataset called
`zaaron_td_with_401_dataflow_metrics` using
`create_or_update_dataflow_sandbox`? [y/n]:
y
>  INFO:root:Test environment, proceeding.
>  Traceback (most recent call last):
>    File "<frozen runpy>", line 198, in _run_module_as_main
>    File "<frozen runpy>", line 88, in _run_code
> File
"/Users/aaron/devel/recidiviz-data/recidiviz/tools/calculator/run_sandbox_calculation_pipeline.py",
line 148, in <module>
>      main()
> File
"/Users/aaron/devel/recidiviz-data/recidiviz/tools/calculator/run_sandbox_calculation_pipeline.py",
line 143, in main
>      run_sandbox_dataflow_pipeline(params, known_args.skip_build)
> File
"/Users/aaron/devel/recidiviz-data/recidiviz/tools/utils/run_sandbox_dataflow_pipeline_utils.py",
line 89, in run_sandbox_dataflow_pipeline
>      params.check_for_valid_input_dataset_overrides(
> File
"/Users/aaron/devel/recidiviz-data/recidiviz/pipelines/pipeline_parameters.py",
line 329, in check_for_valid_input_dataset_overrides
>      raise ValueError(
> ValueError: Found original dataset [normalized_state] in overrides
which is not a dataset this pipeline reads from. Datasets you can
override: ['us_me_normalized_state'].
I think the right solution is to change the input_dataset_overrides_json
from:
{"normalized_state": "zaaron_td_with_401_us_me_normalized_state"}
to:
{"us_me_normalized_state": "zaaron_td_with_401_us_me_normalized_state"}

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: bba1f66b2d46316a173117d9ae31ba2399b3103b