[raw data import] Ignore exceptions when trying to normalize header names if infer_columns_from_config=True (Recidiviz/recidiviz-data#35377)
## Description of the change

In MI we have `infer_columns_from_config=True`, and are seeing error
when reading file headers:
```
  File "/home/airflow/gcs/dags/recidiviz/ingest/direct/raw_data/read_raw_file_column_headers.py", line 143, in _normalize_and_validate_column_headers
    self._validate_csv_no_expected_header_row(
  File "/home/airflow/gcs/dags/recidiviz/ingest/direct/raw_data/read_raw_file_column_headers.py", line 210, in _validate_csv_no_expected_header_row
    normalized_col = normalize_column_name_for_bq(possible_column_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/big_query/big_query_utils.py", line 187, in normalize_column_name_for_bq
    column_name[0] in string.digits
    ~~~~~~~~~~~^^^
IndexError: string index out of range
```
even when we are not expecting a header row we attempt to parse the
first row of the csv as headers to detect the case where we've been sent
a file that unexpectedly does contain a header row. however, if we can't
normalize a cell value to a bq header name we can safely assume that
this value is not a header and we can move on.

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Recidiviz/recidiviz-data#34873

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 432609844dee19969f1c0db3613c88a8ba523015