[Justice Counts] Data Pull filter out demo agencies (Recidiviz/recidiviz-data#25393)
## Description of the change

Today, the CSG Data Pull Script failed with the following error:
```
Traceback (most recent call last):
  File "/Users/michelleorden/.pyenv/versions/3.9.12/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/michelleorden/.pyenv/versions/3.9.12/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/michelleorden/Recidiviz/recidiviz-data/recidiviz/justice_counts/jobs/csg_data_pull.py", line 552, in <module>
    generate_agency_summary_csv(
  File "/Users/michelleorden/Recidiviz/recidiviz-data/recidiviz/justice_counts/jobs/csg_data_pull.py", line 395, in generate_agency_summary_csv
    sorted(datapoints, key=lambda x: x["source_id"]),
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

This occurred because we attempted to sort all datapoints by
`source_id`, however some datapoints have a `source_id = None`. The
`sorted()` function is not able to sort between ints and None values. To
avoid this error, we are doing 2 things
1. Backfill the `source_id` for the newly migrated demo agencies
2. Remove demo agencies from the data pull (should not be in the data
pull in the first place)

How I Tested: I manually ran this script with the current changed and it
succeeded (wrote to the appropriate google sheet)!

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

---------

Co-authored-by: Michelle Orden <michelleorden@Michelles-MBP.attlocal.net>
GitOrigin-RevId: 0d644553ba95f7c8c219c53cf495e96bff0d42c9