unlock attrs lib in pipfile (Recidiviz/recidiviz-data#17704)
## Description of the change

In [attrs 22.2.0](https://pypi.org/project/attrs/22.2.0/): attrs.has()
is now a
[TypeGuard](https://docs.python.org/3/library/typing.html#typing.TypeGuard)
for AttrsInstance. That means that type checkers know a class is an
instance of an attrs class if you check it using attrs.has() (or
attr.has()) first

calling attr.has on cls annotates it with a TypeGuard which I believe is
what is causing the mypy errors of
```recidiviz/common/attr_mixins.py:386: error: "Type[AttrsInstance]" has no attribute "builder"  [attr-defined] recidiviz/common/attr_mixins.py:406: error: "Type[AttrsInstance]" has no attribute "extract_enum_value"  [attr-defined] recidiviz/common/attr_mixins.py:410: error: "Type[AttrsInstance]" has no attribute "extract_date_value"  [attr-defined]```

It doesn't seem necessary attr.has() needs to be called here since in the arguments list cls is already a Type[BuildableAttrType], which is an attr class, but I could be wrong.

## Type of change

> All pull requests must have at least one of the following labels applied (otherwise the PR will fail):

| Label                       	| Description                                                                                               	|
|-----------------------------	|-----------------------------------------------------------------------------------------------------------	|
| Type: Bug                   	| non-breaking change that fixes an issue                                                                   	|
| Type: Feature               	| non-breaking change that adds functionality                                                               	|
| Type: Breaking Change       	| fix or feature that would cause existing functionality to not work as expected                            	|
| Type: Non-breaking refactor 	| change addresses some tech debt item or prepares for a later change, but does not change functionality    	|
| Type: Configuration Change  	| adjusts configuration to achieve some end related to functionality, development, performance, or security 	|
| Type: Dependency Upgrade      | upgrades a project dependency - these changes are not included in release notes                             |

## Related issues

Closes Recidiviz/recidiviz-data#17515

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally Identifiable Information (PII) being mistakenly added in this pull request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

Co-authored-by: Helper Bot <helperbot@recidiviz.org>
GitOrigin-RevId: 008a588bd95717458534d28f7ddb9a8c814bfcb8