[tests] Fix flaky doc generation test (Recidiviz/recidiviz-data#48614)
## Description of the change

`ingest_mappings_schema_documentation_generator_test` is sometimes
failing with

```
FAILED recidiviz/tests/tools/docs/ingest_mappings_schema_documentation_generator_test.py::IngestMappingsSchemaDocumentationGeneratorTest::test_generate_entity_documentation_matches_current_markdown_file - AssertionError: 1 is not false

-   $include_nulls: false
?                   ^

+   $include_nulls: False
?
```

my theory is that if the `raw_data_ruamel_yaml_update` tests run before
the doc generation test the custom bool representer is somehow being
maintained, so we should clear the custom representer once we're done
using it

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Recidiviz/recidiviz-data#47276

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 5743477e09a958a7d505dedc7bded5277389b7e7