[US_CA] Try to fix SFTP by filtering directories, not file paths (Recidiviz/recidiviz-data#38179)
## Description of the change
Last error was ([see here for
context](https://recidiviz.slack.com/archives/C01J3JV7962/p1734641518496849?thread_ts=1734639673.112239&cid=C01J3JV7962)):
```
ValueError: No files found to download for US_CA state. This indicates that the SFTP directory is empty. Please check to see if the state has uploaded any files to SFTP.
```

Thinking the issue with SFTP might be that I was filtering file paths,
not folder paths. Maybe this adjustment will allow the delegate to
discover files?

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes Recidiviz/recidiviz-data#35902

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: a2f6310a1e39fcf73fb15d6afda13e6db94940a6