Update `DirectIngestInstanceStatus` to have a Timezone Aware `status_timestamp` (Recidiviz/recidiviz-data#17211)
## Description of the change

@ageiduschek submitted a
[PR](https://github.com/Recidiviz/recidiviz-data/pull/17079) that was
then [reverted](https://github.com/Recidiviz/recidiviz-data/pull/17198)
because of the following issue

```
>  INFO:root:Schema for table state.state_supervision_violation_response_decision_entry has no excess fields to drop.
>  INFO:root:Schema for table state.state_supervision_violation_response_decision_entry already contains all of the desired fields.
>  Traceback (most recent call last):
>    File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>      return _run_code(code, main_globals, None,
>    File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
>      exec(code, run_globals)
>    File "/Users/anthony/recidiviz/recidiviz-data/recidiviz/persistence/database/bq_refresh/big_query_table_manager.py", line 123, in <module>
>      update_bq_tables_schemas_for_schema_type(
>    File "/Users/anthony/recidiviz/recidiviz-data/recidiviz/persistence/database/bq_refresh/big_query_table_manager.py", line 93, in update_bq_tables_schemas_for_schema_type
>      update_bq_schema_for_sqlalchemy_table(
>    File "/Users/anthony/recidiviz/recidiviz-data/recidiviz/persistence/database/bq_refresh/big_query_table_manager.py", line 66, in update_bq_schema_for_sqlalchemy_table
>      bq_client.update_schema(
>    File "/Users/anthony/recidiviz/recidiviz-data/recidiviz/big_query/big_query_client.py", line 1760, in update_schema
>      raise ValueError(
>  ValueError: Trying to change the field type of an existing field in operations.direct_ingest_instance_status. Existing field timestamp has type DATETIME. Cannot change this type to TIMESTAMP.
Failed with exit code 1
```

To resolve this, this PR adds changes the `timestamp` to
`status_timestamp` and creates a migration to write the timestamp-aware
timestamps to the new column and then delete the old column.

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Will allow us to simplify logic in
https://github.com/Recidiviz/recidiviz-data/pull/16986

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no
"Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

Co-authored-by: Anna Geiduschek <ageiduschek@users.noreply.github.com>
GitOrigin-RevId: 008d29429457d148d3d2b5e1b36932ffacbe3f62