[Airflow] Fix dataflow operator retry / logs (Recidiviz/recidiviz-data#24537)
## Description of the change
The existing implementation of the operator `retry` flow and the error
logs was broken as the `task_id` is now part of a task group and no
longer maps directly to the job name. This updates it so that we use the
job name rather than task id where appropriate.

[Fixes the following
error:](https://941882c9ef884317b481f986ea6d3a40-dot-us-central1.composer.googleusercontent.com/log?dag_id=recidiviz-staging_calculation_dag&execution_date=2023-10-05T20%3A11%3A08.250585%2B00%3A00&map_index=-1&task_id=normalization.us-nd-normalization.run_pipeline)
```

Traceback (most recent call last):
  File "/home/airflow/gcs/dags/recidiviz/airflow/dags/operators/recidiviz_dataflow_operator.py", line 87, in execute
    job = hook.get_job(
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 1075, in get_job
    return jobs_controller.fetch_job_by_id(job_id)
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/dataflow.py", line 263, in fetch_job_by_id
    self._dataflow.projects()
  File "/opt/python3.8/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/opt/python3.8/lib/python3.8/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://dataflow.googleapis.com/v1b3/projects/recidiviz-staging/locations/us-west1/jobs/normalization.us-nd-normalization.run_pipeline?alt=json returned "(218d5cbe3061592e): Information about job normalization.us-nd-normalization.run_pipeline could not be found in our system. Please double check that the API being used is projects.locations.jobs.get (https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.jobs/get). If the API being used is projects.locations.jobs.get, please double check the id (normalization.us-nd-normalization.run_pipeline) is correct. If it is please contact customer support.". Details: "(218d5cbe3061592e): Information about job normalization.us-nd-normalization.run_pipeline could not be found in our system. Please double check that the API being used is projects.locations.jobs.get (https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.jobs/get). If the API being used is projects.locations.jobs.get, please double check the id (normalization.us-nd-normalization.run_pipeline) is correct. If it is please contact customer support.">
[2023-10-05, 21:34:07 UTC] {taskinstance.py:1319} INFO - Marking task as FAILED. dag_id=recidiviz-staging_calculation_dag, task_id=normalization.us-nd-normalization.run_pipeline, execution_date=20231005T201108, start_date=20231005T212326, end_date=20231005T213407
```
## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 23c9e0373604c1006f724f7f2ce338457ee78bb7