[raw data] include multiple error messages if more than one failure occurs during pre-import norm (Recidiviz/recidiviz-data#42409)
## Description of the change

in the past, if there was more than one failure message during
pre-import normalization, we'd arbitrarily pick one; this led to a case
like https://github.com/Recidiviz/recidiviz-data/issues/41897 where the
message lydia was seeing was

```
PIMSContactDashboard] with update_datetime [2025-05-03T11:23:04+00:00] and file_id [1171857] failed:
Chunk [4] of [recidiviz-123-direct-ingest-state-us-ne/unprocessed_2025-05-03T11:23:04:000000_raw_PIMSContactDashboard.csv] skipped due to error encountered with a different chunk with the same input path
```

instead of the actual underling stack trace:
```
Error for file GcsfsFilePath(bucket_name='recidiviz-123-direct-ingest-state-us-ne', blob_name='unprocessed_2025-05-04T11:21:43:000000_raw_PIMSContactDashboard.csv') chunk CsvChunkBoundary(start_inclusive=314573712, end_exclusive=419431585, chunk_num=3): 'charmap' codec can't decode byte 0x90 in position 57955771: character maps to <undefined>
Traceback (most recent call last):
  File "/app/recidiviz/entrypoints/raw_data/normalize_raw_file_chunks.py", line 53, in _normalize_chunks
    results.append(normalizer.normalize_chunk_for_import(chunk))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/recidiviz/ingest/direct/raw_data/direct_ingest_raw_file_pre_import_normalizer.py", line 158, in normalize_chunk_for_import
    decoded_output = output_reader.read()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/app/recidiviz/cloud_storage/read_only_csv_normalizing_stream.py", line 133, in read
    self._add_to_buffer(None)
  File "/app/recidiviz/cloud_storage/read_only_csv_normalizing_stream.py", line 82, in _add_to_buffer
    block = self.fp.read(block_size or -1)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/encodings/cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 57955771: character maps to <undefined>
```

now she \*should\* see both (big if true)

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

only a little big vaguely related to
https://github.com/Recidiviz/recidiviz-data/issues/42277

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: af27daa9d0fb517143518a559bc0d04e7aa30adf