Better string representations of DatabaseEntity objects for debugging (recidiviz/recidiviz-data#3225)
It's very hard to debug certain entity matching errors when the logs look something like:  `Singular ingested entity field state_incarceration_period.source_supervision_violation_response with value: <recidiviz.persistence.database.schema.state.schema.StateSupervisionViolationResponse object at 0x7f85e265d610> ...`. This PR adds a __repr__ function to the DatabaseEntity so we can actually see what database entities are being problematic.

I'm only printing out database id and external id to avoid printing PII to the logs.

Before example log:
recidiviz.persistence.errors.EntityMatchingError: Singular ingested entity field state_charge.court_case with value: <recidiviz.persistence.database.schema.state.schema.StateCourtCase object at 0x11602f278> should match one of the provided db options, but it does not. Found unmatched db entities: [<recidiviz.persistence.database.schema.state.schema.StateCourtCase object at 0x116085588>]

After example log:
recidiviz.persistence.errors.EntityMatchingError: Singular ingested entity field state_charge.court_case with value: StateCourtCase(court_case_id=None, external_id=EXTERNAL_ID-2) should match one of the provided db options, but it does not. Found unmatched db entities: [StateCourtCase(court_case_id=1, external_id=EXTERNAL_ID-1)]

GitOrigin-RevId: d52889310575d95215d6c42a405e4f316a21913f