[US_NC][Not-yet-partner] Add enum value for StateIncarcerationPeriodReleaseReason (Recidiviz/recidiviz-data#20799)
## Description of the change

Extract and merge is failing on this error:
File "/app/recidiviz/common/constants/enum_parser.py", line 121, in
parse
    raise EnumParsingError(self.enum_cls, raw_text)
recidiviz.common.constants.enum_parser.EnumParsingError: Could not parse
RE-ADMISSION when building <enum
'StateIncarcerationPeriodReleaseReason'>"
[(link to
logs)](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-05-08T14:00:25.891Z;query=resource.type%3D%22gae_app%22%0Aresource.labels.module_id%3D%22default%22%0Alog_name%3D%22projects%2Frecidiviz-staging%2Flogs%2Fappengine.googleapis.com%252Fnginx.request%22%0AhttpRequest.requestUrl%3D~%22%2Fdirect%22%0AhttpRequest.requestUrl%3D~%22region%3Dus_nc%22%0AhttpRequest.status!%3D200%0AhttpRequest.requestUrl%20!~%20%22.*secondary.*%22%0Atimestamp%3D%222023-05-08T14:00:25.891Z%22%0AinsertId%3D%22y56dn1g1y3rfo6%22;timeRange=P1D?project=recidiviz-staging)

This change adds `RE-ADMISSION` as a release reason mapping to
`StateIncarcerationPeriodReleaseReason.INTERNAL_UNKNOWN`. There is only
one instance of this value appearing as a release reason, and it is
likely showing up as a release reason because we loosely match start/end
dates with movement dates to extrapolate start/end reasons. This
particular record also has an associated facility value of `COMBINED
RECORDS`, which is the case for < 0.02% of rows in these ingest view
results; there may be other formatting inconsistencies that still need
to be hashed out in those rows.

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: e210c90f354f4e1b88db52e9ff153da9b331191e