[cni] add db migrations for sandbox fixes (Recidiviz/recidiviz-data#94987)
## Description of the change

running sandbox script locally i was gettting `
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation)
value too long for type character varying(255)` for `description` field
and
```
    File "<attrs generated methods recidiviz.persistence.entity.operations.entities.LLMExtractorVersion>", line 41, in __init__
    File "/Users/emilyturner/Recidiviz/recidiviz-data/recidiviz/common/attr_validators.py", line 152, in is_utc_timezone_aware_datetime
      raise ValueError(f"Expected timezone value to be UTC, found: {value.tzinfo}")
  ValueError: Expected timezone value to be UTC, found: UTC-07:00
```
becuase my computer is in pacific time. i updated the helpers in
https://github.com/Recidiviz/recidiviz-data/pull/94985 to correctly set
the timezone but also update types to UTCDatetime so they read back
UTC-labeled on any machine, independent of the DB session timezone

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Part of OBT-32105

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### ⚠️ Changing an opportunity record?
Please [consult this
document](https://www.notion.so/recidiviz/How-to-make-a-change-to-the-Opportunity-Record-1d67889f4d19807f8109f9f2f007dde3)
first to see if additional changes might be required in the admin panel
or a Zod schema. You can confirm with Polaris if unsure.

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 8135a6e9aad5fc1e62672e5ddca064db113ed25f