[ETL] Update Firestore ETL to skip files exported via sandbox DAG runs (Recidiviz/recidiviz-data#26021)
## Description of the change

A fix for this crash we're seeing in
`/practices-etl/_run_firestore_etl`:
```
"Exception on /practices-etl/_run_firestore_etl [POST]
Traceback (most recent call last):
  File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/recidiviz/utils/auth/gae.py", line 59, in auth_and_call
    return func(*args, **kwargs)
  File "/app/recidiviz/workflows/etl/routes.py", line 136, in _run_firestore_etl
    for delegate in get_workflows_delegates(StateCode(state_code)):
  File "/usr/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'sandbox/emily/US_ID' is not a valid _RealStateCode"
timestamp: "2023-12-07T19:04:08.098248Z"
```

This export file is being generated as part of a sandbox calc DAG run
and should be ignored by the ETL.

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Fixes
[this](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-12-07T19:04:16.127Z;duration=P7D;query=resource.type%20%3D%20%22gae_app%22%20httpRequest.requestUrl%20%3D%20%22%2Fpractices-etl%2F_run_firestore_etl%22%0Atimestamp%3D%222023-12-07T19:04:08.101Z%22%0AinsertId%3D%22134txdff298nub%22?project=recidiviz-staging)
crash

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 5bf1225a0f0022aba2073a4b95d9cb519bc278ba