Revert "Add TN to Terraform config lists (Recidiviz/recidiviz-data#5653)" (Recidiviz/recidiviz-data#5817)
This reverts commit e8e7777b3ddabe148c18f81fac3da7ce3bb427bb.

It looks like in Recidiviz/recidiviz-data#5745 when we made the config for the prod-only upload-testing bucket, we failed to gate creation of the cloud function that references that bucket to prod-only as well.

Terraform apply is failing with this error:
```
Error: Error waiting for Creating CloudFunctions Function: Error code 3, message: Cloud Storage trigger bucket recidiviz-staging-direct-ingest-state-us-tn-upload-testing not found

```

(I think we made the MO buckets manually in prod and staging which is why this is happening only now?)

GitOrigin-RevId: 7efb0335709dde4acd90ef737fd8b64224dd9aa5