[US_TX] Add datetime parser (Recidiviz/recidiviz-data#35318)
## Description of the change

reimport failing with
```
Error: Found column [Verified_Employment] on raw file [SupervisionContact] not matching any of the datetime_sql_parsers defined in its configuration YAML.
Defined parsers: [SAFE.PARSE_DATETIME('%y-%m-%d', {col_name})].
First value that does not parse: [2024-04-03].
Validation type: DATETIME_PARSERS
Validation query:
SELECT Verified_Employment
FROM recidiviz-staging.us_tx_secondary_raw_data_temp_load.SupervisionContact__18133__transformed
WHERE Verified_Employment IS NOT NULL AND COALESCE(SAFE.PARSE_DATETIME('%y-%m-%d', Verified_Employment)) IS NULL
LIMIT 1
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Recidiviz/recidiviz-data#35316

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: d81d2b485a5eb947ca3ea0692de124fc403f12c9