[US_IX] map pending custody intake to internal unknown for now (Recidiviz/recidiviz-data#26759)
## Description of the change

Recently saw
```
recidiviz.common.constants.enum_parser.EnumParsingError: Could not parse Pending Custody Intake when building <enum 'StateSupervisionPeriodAdmissionReason'>
```
There's only 1 instance of this, so probably okay just to map to
internal unknown for now.

![image](https://github.com/Recidiviz/recidiviz-data/assets/1537444/da69bc4b-17a0-42a5-b360-7a09c3da9999)

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: c8562cfef28449f96ff6a9f1451a78701cb7578b