Fix ID for `eg_movements` in Ingest View (Recidiviz/recidiviz-data#21147)
## Description of the change

During extract and merge of a raw data pruning run on `eg_movements`,
saw the following:

```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "incarceration_period_external_ids_unique_within_state"
DETAIL:  Key (state_code, external_id)=(US_OZ, 4) already exists
```

`ROW_NUMBER() OVER (PARTITION BY PersonID ORDER BY Date) as ID`
generates duplicate IDs (which become incarceration period
`external_ids`):
<img width="859" alt="Screenshot 2023-05-26 at 1 08 37 PM"
src="https://github.com/Recidiviz/recidiviz-data/assets/8096427/c7a1a4ee-456e-4767-9265-7c9186a26db0">

So instead, just select the `ID` (?):

<img width="978" alt="Screenshot 2023-05-26 at 1 09 43 PM"
src="https://github.com/Recidiviz/recidiviz-data/assets/8096427/cd92887f-5b02-41eb-8fbb-c23772a7513a">

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

N/A

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 6171a3d230825d80500bd7aedfe850e05d3e3f91