[Build] Fix Docker health build on main (Recidiviz/recidiviz-data#11968)
Before my refactor in Recidiviz/recidiviz-data#11874 we used to only initialize the admin panel stores when running in GCP or during local development:
```
        if in_development():
            with local_project_id_override(GCP_PROJECT_STAGING):
                self.all_stores = self._initialize_stores()
        elif in_gcp():
            self.all_stores = self._initialize_stores()
```
This change restores that logic so we don't hit this crash in CI:
```
 File "/app/.venv/lib/python3.8/site-packages/google/cloud/_helpers.py", line 186, in _determine_default_project
    _, project = google.auth.default()
  File "/app/.venv/lib/python3.8/site-packages/google/auth/_default.py", line 488, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

GitOrigin-RevId: 26c85768250448e3687ca17fc805ac42e0b5ab5d