Revert "[tf] add `state_code` labels to state-specific gcs buckets (Recidiviz/recidiviz-data#38987)" (Recidiviz/recidiviz-data#39057)
## Description of the change

This reverts commit 3f5eaf4ade5dbce5f4304c8a87d09024d883217c.

Terraform
[failed](https://console.cloud.google.com/cloud-build/builds;region=us-west1/9d86ddf4-bf2c-489a-a026-d09e9425b501;step=6?project=recidiviz-staging)
with a bunch of errors like

```
Error: googleapi: Error 400: Invalid field "user_labels_list.state_code"; value "US_IX" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "U" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore, invalid
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: f179a89520233817b06a3695148f22c2550c984f