Fixes deploy by ensuring pytablewriter dependency is available beyond just dev packages (Recidiviz/recidiviz-data#20778)
## Description of the change

The staging deploy just failed on the final step, spinning up GAE
workers, with the following error:

```
>    File "/app/recidiviz/server.py", line 35, in <module>
>      from recidiviz.admin_panel.admin_stores import initialize_admin_stores
>    File "/app/recidiviz/admin_panel/admin_stores.py", line 22, in <module>
>      from recidiviz.admin_panel.ingest_metadata_store import IngestDataFreshnessStore
>    File "/app/recidiviz/admin_panel/ingest_metadata_store.py", line 32, in <module>
>      from recidiviz.ingest.direct.ingest_view_materialization.instance_ingest_view_contents import (
>    File "/app/recidiviz/ingest/direct/ingest_view_materialization/instance_ingest_view_contents.py", line 37, in <module>
>      from recidiviz.big_query.view_update_manager import (
>    File "/app/recidiviz/big_query/view_update_manager.py", line 53, in <module>
>      from recidiviz.view_registry.deployed_views import (
>    File "/app/recidiviz/view_registry/deployed_views.py", line 37, in <module>
>      from recidiviz.calculator.query.state.view_config import (
>    File "/app/recidiviz/calculator/query/state/view_config.py", line 22, in <module>
>      from recidiviz.calculator.query.state.views.analyst_data.analyst_data_views import (
>    File "/app/recidiviz/calculator/query/state/views/analyst_data/analyst_data_views.py", line 36, in <module>
>      from recidiviz.calculator.query.state.views.analyst_data.models.analyst_data_view_collector import (
>    File "/app/recidiviz/calculator/query/state/views/analyst_data/models/analyst_data_view_collector.py", line 20, in <module>
>      from pytablewriter import MarkdownTableWriter
>  ModuleNotFoundError: No module named 'pytablewriter'
>  [2023-05-05 16:23:25 -0400] [13] [INFO] Worker exiting (pid: 13)
>  [2023-05-05 16:23:25 -0400] [7] [WARNING] Worker with pid 13 was terminated due to signal 15
>  [2023-05-05 16:23:25 -0400] [7] [WARNING] Worker with pid 14 was terminated due to signal 15
>  [2023-05-05 16:23:25 -0400] [7] [WARNING] Worker with pid 12 was terminated due to signal 15
>  [2023-05-05 16:23:25 -0400] [7] [WARNING] Worker with pid 10 was terminated due to signal 15
>  [2023-05-05 16:23:25 -0400] [7] [INFO] Shutting down: Master
>  [2023-05-05 16:23:25 -0400] [7] [INFO] Reason: Worker failed to boot.
```

As I note here, I believe (but have no hard proof) that this is because
[this file introduced an hour
ago](https://github.com/Recidiviz/recidiviz-data/blob/a9805d094b8c6019e7c1bebfd965b65df7e6937c/recidiviz/calculator/query/state/views/analyst_data/models/analyst_data_view_collector.py)
is the first instance of needing `pytablewriter` in deployed code and
not just local development code. So you wouldn't notice unless you tried
to spin up the GAE app locally that it would fail when the app worker
started roaring through the import paths to start listening to inbound
threads. I believe simply moving the dependency out of --dev will fix
the deploy.

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Follow-up to Recidiviz/recidiviz-data#16785

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

---------

Co-authored-by: Helper Bot <helperbot@recidiviz.org>
GitOrigin-RevId: e56163d69d47be4dd82f39eaae11fd538169194c