[Airflow] Use correct timestamp when fetching Dataflow job error logs (Recidiviz/recidiviz-data#26529)
## Description of the change

`createTime` is the correct key, per
https://cloud.google.com/dataflow/docs/reference/rpc/google.dataflow.v1beta3#job

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/gcs/dags/recidiviz/airflow/dags/operators/recidiviz_dataflow_operator.py", line 113, in execute
    job_creation_time=job["creationTime"],
KeyError: 'creationTime'
```

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 5826f3526a40097daea2f5b4f17202438b968357