[Bugfix] Add better log for non-ExternalIdEntity merging errors (Recidiviz/recidiviz-data#33537)
## Description of the change

Elise had a pipeline crash with a very unhelpful error message:
```
ValueError: Found duplicate item [1980-03-27T00:00:00-None-] in list within the same entity tree- merging before this step should have eliminated this duplicate already.
```

Hopefully after this fix we'll get more useful info with the stack
trace.

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

See thread:
https://recidiviz.slack.com/archives/C01J3JV7962/p1726853274427269

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 0334a25a14f4c27e5283f6c045c3349a2acfed92