[airflow] Isolate `recidiviz.airflow.dags.monitoring.recidiviz_github_alerting_service` logger (Recidiviz/recidiviz-data#53807)
## Description of the change

Airflow tests are failing on
https://github.com/Recidiviz/recidiviz-data/pull/51897 with
```
FAILED tests/monitoring/recidiviz_github_alerting_service_test.py::RecidivizGitHubServiceTest::test_existing_incident_ongoing_update_and_reopen - AssertionError: assert 9 == 1
 +  where 9 = len(['INFO:root:Found out-of-date issue [Recidiviz/recidiviz-data#54321] for an incident [Task Run: test_dag.a.job.id, started: 2024-01-01 00:00 U...nexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n', ...])
 +    where ['INFO:root:Found out-of-date issue [Recidiviz/recidiviz-data#54321] for an incident [Task Run: test_dag.a.job.id, started: 2024-01-01 00:00 U...nexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n', ...] = _LoggingWatcher(records=[<LogRecord: root, 20, /home/runner/_work/recidiviz-data/recidiviz-data/recidiviz/airflow/dags...on unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n']).output
```

even though the change is not at all related to `RecidivizGitHubService`
and the test passes locally

i think that when the unit tests are run in parallel multiple other
tests' log statements are being capture by the `assertLogs`. when i add
this commit on top of my changes in Recidiviz/recidiviz-data#51897 then tests pass

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### ⚠️ Changing an opportunity record?
Please [consult this
document](https://www.notion.so/recidiviz/How-to-make-a-change-to-the-Opportunity-Record-1d67889f4d19807f8109f9f2f007dde3)
first to see if additional changes might be required in the admin panel
or a Zod schema. You can confirm with Polaris if unsure.

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: f26ca563a44ab6334064b856efb2090b7dd3f9f3