[US_IX] Map P&P PSI SECTION SUPERVISOR to SUPERVISION_OFFICER_SUPERVISOR staff role subtype (Recidiviz/recidiviz-data#89315)
## Description of the change

Adds a mapping for the raw `EmployeeTypeName` value `P&P PSI SECTION
SUPERVISOR` to `StateStaffRoleSubtype.SUPERVISION_OFFICER_SUPERVISOR` in
`us_ix_state_staff_role_location_periods.yaml`.

This new value was appearing in ATLAS data with no corresponding entry
in the `role_subtype` `$enum_mapping`, causing the ingest pipeline to
fail with:

```
EnumParsingError: Could not parse P&P PSI SECTION SUPERVISOR when building <enum 'StateStaffRoleSubtype'>
```

It's mapped alongside the existing `P&P SECTION SUPERVISOR` value, which
maps to the same subtype.

## Type of change

Type: Bug

## Related issues

N/A

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 2dd7dbd5f7a5e7cf253b61d874218a58d72d57af