Revert "[Ingest] Make ingest instance timestamps timezone aware" (Recidiviz/recidiviz-data#17198)
Reverts Recidiviz/recidiviz-dataRecidiviz/recidiviz-data#17079 which is blocking the staging
deploy with the following error:

```
>  INFO:root:Schema for table state.state_supervision_violation_response_decision_entry has no excess fields to drop.
>  INFO:root:Schema for table state.state_supervision_violation_response_decision_entry already contains all of the desired fields.
>  Traceback (most recent call last):
>    File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>      return _run_code(code, main_globals, None,
>    File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
>      exec(code, run_globals)
>    File "/Users/anthony/recidiviz/recidiviz-data/recidiviz/persistence/database/bq_refresh/big_query_table_manager.py", line 123, in <module>
>      update_bq_tables_schemas_for_schema_type(
>    File "/Users/anthony/recidiviz/recidiviz-data/recidiviz/persistence/database/bq_refresh/big_query_table_manager.py", line 93, in update_bq_tables_schemas_for_schema_type
>      update_bq_schema_for_sqlalchemy_table(
>    File "/Users/anthony/recidiviz/recidiviz-data/recidiviz/persistence/database/bq_refresh/big_query_table_manager.py", line 66, in update_bq_schema_for_sqlalchemy_table
>      bq_client.update_schema(
>    File "/Users/anthony/recidiviz/recidiviz-data/recidiviz/big_query/big_query_client.py", line 1760, in update_schema
>      raise ValueError(
>  ValueError: Trying to change the field type of an existing field in operations.direct_ingest_instance_status. Existing field timestamp has type DATETIME. Cannot change this type to TIMESTAMP.
Failed with exit code 1
```

GitOrigin-RevId: 4c01a81be9785ab2d029510b6468f6c3ff503ba5