[Airflow] Return normally if we can't connect to cloudsql proxy sidecar during shutdown (Recidiviz/recidiviz-data#35060)
## Description of the change

We're seeing some airflow tasks fail with
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=9091): Max retries exceeded with url: /quitquitquit (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x78e5f01bc110>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
Something is sending a [SIGTERM to the
container](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22recidiviz-staging%22%0Aresource.labels.location%3D%22us-central1%22%0Aresource.labels.cluster_name%3D%22us-central1-orchestration-v-39056c2e-gke%22%0Aresource.labels.namespace_name%3D%22composer-user-workloads%22%0Aresource.labels.pod_name%3D%22ingest-pipeline-should-run-in-dag-fk3jw14s%22%0Aresource.labels.container_name%3D%22cloud-sql-proxy%22;pinnedLogId=2024-11-11T11:06:48.981183789Z%2Fdtyq4tf6ncwkx97v;cursorTimestamp=2024-11-11T11:06:48.981183789Z;startTime=2024-11-11T11:00:00Z;endTime=2024-11-11T11:15:00Z?project=recidiviz-staging)
so it's being shutdown before we can gracefully terminate. I don't know
exactly what is happening but i don't think it's task-failure-worthy if
we try to gracefully shutdown the sidecar and its already shutdown

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Recidiviz/recidiviz-data#34949

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 87b1af14dabe68e86c722293c3f34103774e5a19