[Deploy] A couple logging updates (Recidiviz/recidiviz-data#18514)
## Description of the change

This fixes a few small usability issues I noticed when handling the
deploy yesterday.

1. The prompt accepted response line was not written until after you
replied `y/n`, for example it would only show:
```
>  failed to deploy all views - retry?

```
rather than
```
>  failed to deploy all views - retry?
>  Please type "yes" to confirm. (Anything else exits):
```
2. We lost some context for exceptions encountered while deploying
views. A view update was failing due one of its dependent tables not
existing. The log read:
```
>  WARNING:root:<class 'ValueError'> Error creating or updating view [BigQueryAddress(dataset_id='deploy_68efea_reference_views', table_id='ingested_product_users')]
>  failed to deploy all views - retry?
```

Previously we'd get the full trace / exception chain info, for example:
```
>  Traceback (most recent call last):
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 455, in process_fn
>      return _create_or_update_view_and_materialize_if_necessary(
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 480, in _create_or_update_view_and_materialize_if_necessary
>      if not view.should_deploy():
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/big_query_view.py", line 127, in should_deploy
>      self._should_deploy = self._should_deploy_predicate()
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/big_query_table_checker.py", line 53, in has_column
>      return self._table_has_column(col)
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/big_query_table_checker.py", line 46, in _table_has_column
>      return col_name in self.columns
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/big_query_table_checker.py", line 38, in columns
>      t = bq_client.get_table(
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/big_query_client.py", line 903, in get_table
>      return self.client.get_table(table_ref)
>    File "/Users/danhansen/.local/share/virtualenvs/recidiviz-data-HZaH0hQ3/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 1034, in get_table
>      api_response = self._call_api(
>    File "/Users/danhansen/.local/share/virtualenvs/recidiviz-data-HZaH0hQ3/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
>      return call()
>    File "/Users/danhansen/.local/share/virtualenvs/recidiviz-data-HZaH0hQ3/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
>      return retry_target(
>    File "/Users/danhansen/.local/share/virtualenvs/recidiviz-data-HZaH0hQ3/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
>      return target()
>    File "/Users/danhansen/.local/share/virtualenvs/recidiviz-data-HZaH0hQ3/lib/python3.9/site-packages/google/cloud/_http.py", line 484, in api_request
>      raise exceptions.from_http_response(response)
>  google.api_core.exceptions.NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/recidiviz-123/datasets/validation_external_accuracy/tables/supervision_population_person_level_materialized?prettyPrint=false: Not found: Table recidiviz-123:validation_external_accuracy.supervision_population_person_level_materialized
>
>  The above exception was the direct cause of the following exception:
>
>  Traceback (most recent call last):
>    File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>      return _run_code(code, main_globals, None,
>    File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
>      exec(code, run_globals)
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/tools/deploy/deploy_views.py", line 163, in <module>
>      deploy_views(
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/tools/deploy/deploy_views.py", line 148, in deploy_views
>      create_managed_dataset_and_deploy_views_for_view_builders(
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 250, in create_managed_dataset_and_deploy_views_for_view_builders
>      raise e
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 240, in create_managed_dataset_and_deploy_views_for_view_builders
>      _create_managed_dataset_and_deploy_views(
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 461, in _create_managed_dataset_and_deploy_views
>      results = dag_walker.process_dag(process_fn)
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/big_query_view_dag_walker.py", line 369, in process_dag
>      raise e
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/big_query_view_dag_walker.py", line 361, in process_dag
>      execution_sec, view_result = future.result()
>    File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 439, in result
>      return self.__get_result()
>    File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
>      raise self._exception
>    File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>      result = self.fn(*self.args, **self.kwargs)
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/utils/trace.py", line 63, in _wrapper
>      res = span(func)(*args, **kwargs)
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/utils/trace.py", line 96, in run_inside_new_span
>      return func(*args, **kwargs)
>    File "/Users/danhansen/.local/share/virtualenvs/recidiviz-data-HZaH0hQ3/lib/python3.9/site-packages/opencensus/common/runtime_context/__init__.py", line 85, in call_with_current_context
>      return func(*args, **kwargs)
>    File "/Users/danhansen/workspace/on-call/recidiviz-data/recidiviz/big_query/view_update_manager.py", line 459, in process_fn
>      raise ValueError(f"Error creating or updating view [{v.address}]") from e
>  ValueError: Error creating or updating view [BigQueryAddress(dataset_id='deploy_f65e20_validation_metadata', table_id='validation_metadata__supervision_population_person_level_materialized__supervision_level')]
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no
"Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 0029dab12f030d96c020816336975096aaa0d3ed