[raw data] only check date bounds conditionally for `deprecate_ingest_bucket_raw_files` (Recidiviz/recidiviz-data#37415)
## Description of the change

fixes this error
```
(recidiviz-data) recidiviz-data(main)$  python -m recidiviz.tools.ingest.operations.deprecate_ingest_bucket_raw_files --state-code US_ME --project-id recidiviz-staging --file-tag-filters SUPERVISION_POPULATION_BY_OFFICER --ingest-instance PRIMAR
Y
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/oro/recidiviz/recidiviz-data/recidiviz/tools/ingest/operations/deprecate_ingest_bucket_raw_files.py", line 175, in <module>
    main()
  File "/Users/oro/recidiviz/recidiviz-data/recidiviz/tools/ingest/operations/deprecate_ingest_bucket_raw_files.py", line 118, in main
    if args.start_date_bound > args.end_date_bound:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

n/a

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 744acf8dd8bfca6a91f8ef8988fa627c7b155965