[Deploy] Create Airflow source files manifest outside of Terraform plan lifecycle (Recidiviz/recidiviz-data#33011)
## Description of the change
[While developing the Terraform Cloud Build step, the following error
was
raised:](https://console.cloud.google.com/cloud-build/builds;region=us-west1/c3d27960-cd38-4887-9aed-24b633b4f67a;step=2?project=recidiviz-staging)

```
Error: exec: "pipenv": executable file not found in $PATH
Program: "pipenv"
Platform: linux
```

This is because Terraform is running inside of a Terraform-only image.
Rather than re-build the Terraform Dockerfile to include artifacts from
our base image, it seemed easier to read the source file manifest from a
file.

In the upcoming Cloud Build, we will download the release candidate
image, run the Airflow source files script and write to a shared volume,
and then proceed with the plan.

It still feels like we'll be able to do most deployment work without
using the `dev-packages` from our Pipfile, or creating a specific
"deployment runner" image. However, if we were to do so, we could revert
this diff.

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Recidiviz/recidiviz-data#33010

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: f5aa4073a05776131064938358689c3e56bbd4b2