[Bugfix] Fix log exception logging issue in BigQueryDagWalker (Recidiviz/recidiviz-data#15648)
## Description of the change

I broke our ability to observe why nodes in the BQ graph are crashing by
doing `raise e from ValueError()` in an `except` statement.

Crash stacks now don't actually include the original crash. For example:
```
Exception on /cloud_sql_to_bq/refresh_bq_schema/STATE [POST]
ValueError: Exception found fetching result for view_key: [DagKey(view_address=BigQueryAddress(dataset_id='state_v2_us_id_primary_cloudsql_connection', table_id='us_id_state_incarceration_period'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.venv/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/recidiviz/utils/auth/gae.py", line 101, in auth_and_call
    return func(*args, **kwargs)
  File "/app/recidiviz/persistence/database/bq_refresh/cloud_sql_to_bq_refresh_control.py", line 172, in refresh_bq_schema
    federated_bq_schema_refresh(schema_type=schema_type)
  File "/app/recidiviz/persistence/database/bq_refresh/federated_cloud_sql_to_bq_refresh.py", line 86, in federated_bq_schema_refresh
    refreshed_states = _federated_bq_regional_dataset_refresh(
  File "/app/recidiviz/persistence/database/bq_refresh/federated_cloud_sql_to_bq_refresh.py", line 199, in _federated_bq_regional_dataset_refresh
    create_managed_dataset_and_deploy_views_for_view_builders(
  File "/app/recidiviz/big_query/view_update_manager.py", line 237, in create_managed_dataset_and_deploy_views_for_view_builders
    raise e
  File "/app/recidiviz/big_query/view_update_manager.py", line 227, in create_managed_dataset_and_deploy_views_for_view_builders
    _create_managed_dataset_and_deploy_views(
  File "/app/recidiviz/big_query/view_update_manager.py", line 385, in _create_managed_dataset_and_deploy_views
    results = dag_walker.process_dag(process_fn)
  File "/app/recidiviz/big_query/big_query_view_dag_walker.py", line 350, in process_dag
    raise e from ValueError(
  File "/app/recidiviz/big_query/big_query_view_dag_walker.py", line 346, in process_dag
    execution_sec, view_result = future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/recidiviz/big_query/big_query_view_dag_walker.py", line 623, in _wrapper
    res = trace.span(func)(view, parent_results)
  File "/app/recidiviz/utils/trace.py", line 79, in run_inside_new_span
    return func(*args, **kwargs)
  File "/app/.venv/lib/python3.9/site-packages/opencensus/common/runtime_context/__init__.py", line 85, in call_with_current_context
    return func(*args, **kwargs)
  File "/app/recidiviz/big_query/view_update_manager.py", line 383, in process_fn
    raise ValueError(f"Error creating or updating view [{v.address}]") from e
ValueError: Error creating or updating view [BigQueryAddress(dataset_id='state_v2_us_id_primary_cloudsql_connection', table_id='us_id_state_incarceration_period')]
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Will help debug
[this](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-09-27T13:00:10.462435Z;query=%2528%0A%20%20%20%20%2528resource.type%3D%22gae_app%22%20resource.labels.module_id%3D%22default%22%20log_id%2528%22appengine.googleapis.com%2Fnginx.request%22%2529%2529%0A%20%20%20%20OR%20%2528resource.type%3D%22cloud_run_revision%22%20resource.labels.service_name%3D%22case-triage-web%22%20severity%3D%22ERROR%22%20log_id%2528%22run.googleapis.com%2Fstderr%22%2529%20sample%2528insertId,%200.1%2529%2529%0A%20%20%20%20OR%20%2528resource.type%3D%22cloud_run_revision%22%20resource.labels.service_name%3D%22justice-counts-web%22%20severity%3D%22ERROR%22%2529%0A%20%20%20%20OR%20%2528resource.type%3D%22cloud_run_revision%22%20resource.labels.service_name%3D%22application-data-import%22%20severity%3D%22ERROR%22%2529%0A%2529%0A-httpRequest.status%3D200%0A-httpRequest.status%3D201%0A-httpRequest.status%3D304%0A-httpRequest.status%3D308%0A-httpRequest.requestUrl%3D%22%2Ffavicon.ico%22%0A-httpRequest.requestUrl%3D~%22%2Fbatch%2Fread_and_persist%22%0A-httpRequest.requestUrl%3D~%22%2Fscraper%2F%22%0A-httpRequest.requestUrl%3D~%22%2Fscrape_aggregate_reports%2F%22%0A-httpRequest.requestUrl%3D~%22%2Fdirect%2F.*%5C%3Fregion%3Dus_%5B%5B:alpha:%5D%5D%7B2%7D_.*%22%0A-httpRequest.requestUrl%3D~%22%2Fcloud_function%2Fstate_aggregate%22%0A-httpRequest.requestUrl%3D~%22%2Finfer_release%2F%22%0A-httpRequest.requestUrl%3D~%22%2Fjustice_counts%2Fingest%22%0A-httpRequest.requestUrl%3D~%22%2Fadmin%2Fapi%2Fcase_triage%22%0A-httpRequest.requestUrl%3D%22%2F%22%0AhttpRequest.requestUrl%3D%22%2Fcloud_sql_to_bq%2Frefresh_bq_schema%2FSTATE%22%0Atimestamp%3D%222022-09-27T13:11:44.280Z%22%0AinsertId%3D%221jhtwiif6z7vvl%22;summaryFields=:false:32:beginning:false;timeRange=P4D?project=recidiviz-123)
crash.

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] This pull request has been moved out of a Draft state, has no
"Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 2f76f554c645caf23387964719cda65443ea85e8