Revert "Add TN to Terraform config lists (recidiviz/recidiviz-data#5653)" (recidiviz/recidiviz-data#5817)
This reverts commit ce9616d59e2f4ed610a7af795d92acb2aa37f00e.

It looks like in recidiviz/recidiviz-data#5745 when we made the config for the prod-only upload-testing bucket, we failed to gate creation of the cloud function that references that bucket to prod-only as well.

Terraform apply is failing with this error:
```
Error: Error waiting for Creating CloudFunctions Function: Error code 3, message: Cloud Storage trigger bucket recidiviz-staging-direct-ingest-state-us-tn-upload-testing not found

```

(I think we made the MO buckets manually in prod and staging which is why this is happening only now?)

GitOrigin-RevId: 7f093dfffe9a9d21eba71eca53398886b1ee65bb