[BigQuery] Allow dataflow sandbox dataset to match standard sandbox dataset name (Recidiviz/recidiviz-data#15523)
## Description of the change

Fix for this crash @gheidkamp11 was seeing:
```
INFO:root:Updating 261 views...
INFO:root:Overriding [dataflow_metrics] dataset with [mo_secondary_validation_dataflow_metrics].
Traceback (most recent call last):
 File "/usr/local/Cellar/python@3.9/3.9.13_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
  return _run_code(code, main_globals, None,
 File "/usr/local/Cellar/python@3.9/3.9.13_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
  exec(code, run_globals)
 File "/Users/genevieveheidkamp/Recidiviz/recidiviz-data/recidiviz/tools/load_views_to_sandbox.py", line 611, in <module>
  _load_manually_filtered_views_to_sandbox(
 File "/Users/genevieveheidkamp/Recidiviz/recidiviz-data/recidiviz/tools/load_views_to_sandbox.py", line 225, in _load_manually_filtered_views_to_sandbox
  _load_collected_views_to_sandbox(
 File "/Users/genevieveheidkamp/Recidiviz/recidiviz-data/recidiviz/tools/load_views_to_sandbox.py", line 471, in _load_collected_views_to_sandbox
  sandbox_address_overrides = address_overrides_for_view_builders(
 File "/Users/genevieveheidkamp/Recidiviz/recidiviz-data/recidiviz/view_registry/address_overrides_factory.py", line 125, in address_overrides_for_view_builders
  address_overrides_builder.register_custom_dataset_override(
 File "/Users/genevieveheidkamp/Recidiviz/recidiviz-data/recidiviz/big_query/address_overrides.py", line 229, in register_custom_dataset_override
  raise ValueError(
ValueError: The new_dataset_id [mo_secondary_validation_dataflow_metrics] matches the standard sandbox override for original_dataset_id [dataflow_metrics]. Should use register_sandbox_override_for_entire_dataset to set a standard sandbox override for a dataset.
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

See slack
[thread](https://recidiviz.slack.com/archives/C01J3JV7962/p1663799162116019)

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] This pull request has been moved out of a Draft state, has no
"Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 5c16ba3cf65906bc380db2970a0d8dc691d77238