Fix the dev mode build of Dockerfile.recidiviz-base by installing lsb-release. (Recidiviz/recidiviz-data#27049)
## Description of the change

Fix the dev mode build of `Dockerfile.recidiviz-base` by installing `
lsb-release`.

Building a Docker image using `Dockerfile.recidiviz-base` with the build
arg `DEV_MODE=True` results in the error logs attached below.

The specific script used was `docker build . -f
Dockerfile.recidiviz-base -t
us-central1-docker.pkg.dev/justice-counts-staging/recidiviz-base-images/recidiviz-base:latest
--platform=linux/amd64 --build-arg DEV_MODE=True`.

@ohaibbq fixed this by adding `lsb-release` to the list of installations
in `Dockerfile.recidiviz-base`.

Submitting this as a one line fix since we are referencing the command
above in the JC ReadMe.

## Testing
Tested this locally and the dev recidiviz-base image built successfully.

```
[+] Building 86.1s (9/14)                                                   docker:desktop-linux
 => [internal] load .dockerignore                                                           0.0s
 => => transferring context: 3.19kB                                                         0.0s
 => [internal] load build definition from Dockerfile.recidiviz-base                         0.0s
 => => transferring dockerfile: 2.94kB                                                      0.0s
 => [internal] load metadata for docker.io/library/ubuntu:mantic-20231011                   1.9s
 => [ 1/10] FROM docker.io/library/ubuntu:mantic-20231011@sha256:4c32aacd0f7d1d3a29e82bee7  3.2s
 => => resolve docker.io/library/ubuntu:mantic-20231011@sha256:4c32aacd0f7d1d3a29e82bee76f  0.0s
 => => sha256:f906b88252effff97383eeb7dd4d265f3f31a54aa3833dd349cf8c4a35 26.38MB / 26.38MB  2.5s
 => => sha256:4c32aacd0f7d1d3a29e82bee76f892ba9bb6a63f17f9327ca0d97c3d39b9 1.13kB / 1.13kB  0.0s
 => => sha256:7708743264cbb7f6cf7fc13e915faece45a6cdda455748bc55e58e8de3d27b63 424B / 424B  0.0s
 => => sha256:3f9cf3a31fbf871322b774402c7c25b800d0e93c222d5a44339f2d3a99de 2.31kB / 2.31kB  0.0s
 => => extracting sha256:f906b88252effff97383eeb7dd4d265f3f31a54aa3833dd349cf8c4a35fbdbe9   0.6s
 => [internal] load build context                                                           0.0s
 => => transferring context: 136B                                                           0.0s
 => [ 2/10] RUN apt update -y &&     apt install -y     locales     git     libxml2-dev l  76.6s
 => [ 3/10] RUN locale-gen en_US.UTF-8                                                      0.8s
 => [ 4/10] RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime                  0.1s
 => ERROR [ 5/10] RUN if [ "True" = "True" ];     then apt-get install wget &&     wget --  3.5s
------
 > [ 5/10] RUN if [ "True" = "True" ];     then apt-get install wget &&     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - &&     echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list &&     apt-get update && apt-get install postgresql-13 -y;     fi:
0.106 Reading package lists...
0.376 Building dependency tree...
0.443 Reading state information...
0.527 The following NEW packages will be installed:
0.527   wget
1.069 0 upgraded, 1 newly installed, 0 to remove and 9 not upgraded.
1.069 Need to get 331 kB of archives.
1.069 After this operation, 930 kB of additional disk space will be used.
1.069 Get:1 http://ports.ubuntu.com/ubuntu-ports mantic/main arm64 wget arm64 1.21.3-1ubuntu1 [331 kB]
1.582 debconf: delaying package configuration, since apt-utils is not installed
1.594 Fetched 331 kB in 1s (351 kB/s)
1.601 Selecting previously unselected package wget.
(Reading database ... 37208 files and directories currently installed.)
1.611 Preparing to unpack .../wget_1.21.3-1ubuntu1_arm64.deb ...
1.612 Unpacking wget (1.21.3-1ubuntu1) ...
1.626 Setting up wget (1.21.3-1ubuntu1) ...
1.656 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
2.035 OK
2.040 /bin/sh: 1: lsb_release: not found
2.040 deb http://apt.postgresql.org/pub/repos/apt/ -pgdg main
2.511 Hit:1 http://ports.ubuntu.com/ubuntu-ports mantic InRelease
2.581 Hit:2 http://ports.ubuntu.com/ubuntu-ports mantic-updates InRelease
2.662 Hit:3 http://ports.ubuntu.com/ubuntu-ports mantic-backports InRelease
2.738 Hit:4 http://ports.ubuntu.com/ubuntu-ports mantic-security InRelease
3.014 Ign:5 http://apt.postgresql.org/pub/repos/apt -pgdg InRelease
3.121 Err:6 http://apt.postgresql.org/pub/repos/apt -pgdg Release
3.121   404  Not Found [IP: 87.238.57.227 80]
3.129 Reading package lists...
3.443 E: The repository 'http://apt.postgresql.org/pub/repos/apt -pgdg Release' does not have a Release file.
------
Dockerfile.recidiviz-base:40
--------------------
  39 |     # Install postgres to be used by tests that need to write to a database from multiple threads.
  40 | >>> RUN if [ "$DEV_MODE" = "True" ]; \
  41 | >>>     then apt-get install wget && \
  42 | >>>     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
  43 | >>>     echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list && \
  44 | >>>     apt-get update && apt-get install postgresql-13 -y; \
  45 | >>>     fi
  46 |     # Add all the postgres tools installed above to the path, so that we can use pg_ctl, etc. in tests.
--------------------
ERROR: failed to solve: process "/bin/sh -c if [ \"$DEV_MODE\" = \"True\" ];     then apt-get install wget &&     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - &&     echo \"deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main\" | tee /etc/apt/sources.list.d/pgdg.list &&     apt-get update && apt-get install postgresql-13 -y;     fi" did not complete successfully: exit code: 100
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 26b4ac91424687001610fce17a32928e636b08bd