[US_TX] Map supervision violation condition code O.37 to TECHNICAL (Recidiviz/recidiviz-data#86305)
## Description of the change

Adds the violation condition code `O.37` to the
`StateSupervisionViolationType.TECHNICAL` mapping in
`us_tx_supervision_violation.yaml`.

The TX ingest mapping enumerates every known `O.xx` condition code and
maps them all to `TECHNICAL`, but `O.37` was missing (the list jumped
from `O.36` to `O.38`). When that raw value appeared in
`condition_array` (sourced from `VIOLATION_CONDITION` in the
`Violations` raw table), the enum parser had no mapping and the
normalization pipeline failed with:

```
recidiviz.common.constants.enum_parser.EnumParsingError: Could not parse O.37 when building <enum 'StateSupervisionViolationType'>
```

Mapping `O.37` to `TECHNICAL` is consistent with how all other `O.xx`
codes are handled.

## Type of change

Type: Bug

## Related issues

N/A

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

### Code review

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: a722d35298ea3770cc7d4e2147fdb3d55f7d50af