[US_NC][Not-yet-partner] Add state-specific incarceration normalization logic (Recidiviz/recidiviz-data#20427)
## Description of the change

Normalization was failing in NC with this error:
```
ValueError: Unexpected ingest-only admission_reason ADMITTED_FROM_SUPERVISION on ip: <redacted>
We should have handled this value by the end of IP normalization. [while running 'Normalize entities']
```

From the StateIncarcerationPeriodAdmissionReason docs:
`ADMITTED_FROM_SUPERVISION` is an ingest-only enum, and should only be
used as a placeholder at ingest time if we are unable to determine
whether an admission from supervision to prison is a sanction,
revocation, or temporary custody admission. All periods with this value
must be updated by the state’s IP normalization process to set the
accurate admission reason.

This error was occuring because the state-specific incarceration
normalization delegate did not have any methods defined to update IP's
with `ADMITTED_FROM_SUPERVISION` admission reasons. Since we don't have
much information to work with in figuring out the exact nature of these
admissions, as a placeholder all incarceration periods with an
`ADMITTED_FROM_SUPERVISION` admission reason will be normalized to have
`REVOCATION` as an admission reason.

For reference, the raw data values that map to
`ADMITTED_FROM_SUPERVISION` are `RETURNED FROM PAROLE` and
`RE-ADMISSION`.

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] This pull request has been moved out of a Draft state, has no
"Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: da4d2ddf349ee934ea50c689418970f43d1fac16