Casts attribute columns as string before inclusion in partition in `aggregate_adjacent_spans` (Recidiviz/recidiviz-data#21283)
## Description of the change

Fixes bug that was throwing error below because a float-typed column was
passed into `aggregate_adjacent_spans` and used in a partition. Changes
to cast all attribute columns to STRING when used in a partition
statement.

```
>  ValueError: Error creating or updating view [BigQueryAddress(dataset_id='deploy_a27153_sessions', table_id='justice_impact_sessions')]
...
>  ValueError: Cannot update view query for [deploy_a27153_sessions.justice_impact_sessions]
...
>  google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/recidiviz-staging/datasets/deploy_a27153_sessions/tables?prettyPrint=false: Partitioning by expressions of type FLOAT64 is not allowed at [75:92]
```

Tested sandbox and `justice_impact_sessions` no longer hits an error.

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

Co-authored-by: mayukas <mayuka@stanford.edu>
GitOrigin-RevId: 2b87639616c91d119640d602de80b5fc48a9bb28