Add tool to run mappings against latest view results (Recidiviz/recidiviz-data#15989)
## Description of the change

We frequently run into ingest issues with new views where something
isn't handled by the mappings. This might be an enum value that we
forgot to map, or frequently a bad date in the raw data. The turnaround
time on fixing these can be long because we don't notice until the
ingest run crashes, and then we have to fix the issue and wait for it to
crash again. This allows you to run the results of the ingest view
through the mappings and make sure they all parse successfully.

If it works:

```
$  python -m recidiviz.tools.ingest.development.run_mappings_against_ingest_view_results \
        --project-id recidiviz-staging \
        --state-code US_ND \
        --ingest-view-name elite_alias
Test environment, proceeding.
Running `elite_alias` view query against latest raw data tables...
Query completed.
Parsing results...
  logs at /var/folders/xl/1fld2d1j4ds_kfgb_h2y1c5h0000gn/T/mappings_results.txt
100%|█████████████████████████████████████████████████████████████████████████████████| 17747/17747 [00:06<00:00, 2893.91it/s]
Parsed successfully.
```

If there are failures:

```
$ python -m recidiviz.tools.ingest.development.run_mappings_against_ingest_view_results \
        --project-id recidiviz-staging \
        --state-code US_PA \
        --ingest-view-name program_assignment
Test environment, proceeding.
Running `program_assignment` view query against latest raw data tables...
Query completed.
Parsing results...
  logs at /var/folders/xl/1fld2d1j4ds_kfgb_h2y1c5h0000gn/T/mappings_results.txt
 76%|████████████████████████████████████████████████████████████▍                  | 177504/232178 [01:03<00:29, 1848.43it/s]
Error: cannot parse date: 2013-02-30
100%|███████████████████████████████████████████████████████████████████████████████| 232178/232178 [01:22<00:00, 2814.89it/s]
Parsing completed with 1 failures, see failures at /var/folders/xl/1fld2d1j4ds_kfgb_h2y1c5h0000gn/T/mappings_results.txt
```

The log output then has the row number (not consistent so maybe not that
helpful), but also the actual row output along with the error:

```
$ tail -f /var/folders/xl/1fld2d1j4ds_kfgb_h2y1c5h0000gn/T/mappings_results.txt
### Row 177598
Ingest View Result: {'ParoleNumber': 'REDACTED', 'ParoleCountID': '2', 'TreatmentID': '5', 'TrtStatusCode': '', 'TrtClassCode': '2002', 'classification_description': 'Domestic Relations', 'TrtProgramDescription': 'TRIAD TREATMENT', 'TrtProgramCode': 'REF', 'TrtDo': '03', 'TrtCounty': '67', 'TrtStartDateYear': '2013', 'TrtStartDateMonth': '02', 'TrtStartDateDay': '30', 'TrtEndDateYear': '', 'TrtEndDateMonth': '', 'TrtEndDateDay': ''}
Traceback (most recent call last):
  File "/Users/colin/code/recidiviz-data/recidiviz/ingest/direct/ingest_mappings/ingest_view_results_parser.py", line 73, in parse
    output_tree = output_manifest.build_from_row(row)
  File "/Users/colin/code/recidiviz-data/recidiviz/ingest/direct/ingest_mappings/ingest_view_manifest.py", line 196, in build_from_row
    field_value = field_manifest.build_from_row(row)
  File "/Users/colin/code/recidiviz-data/recidiviz/ingest/direct/ingest_mappings/ingest_view_manifest.py", line 634, in build_from_row
    child_entity = child_manifest.build_from_row(row)
  File "/Users/colin/code/recidiviz-data/recidiviz/ingest/direct/ingest_mappings/ingest_view_manifest.py", line 200, in build_from_row
    entity = self.entity_factory_cls.deserialize(**args)
  File "/Users/colin/code/recidiviz-data/recidiviz/persistence/entity/state/deserialize_entity_factories.py", line 220, in deserialize
    return entity_deserialize(
  File "/Users/colin/code/recidiviz-data/recidiviz/persistence/entity/entity_deserialize.py", line 168, in entity_deserialize
    converted_args[field_name] = convert_field_value(field_, kwargs[field_name])
  File "/Users/colin/code/recidiviz-data/recidiviz/persistence/entity/entity_deserialize.py", line 130, in convert_field_value
    return parse_date(field_value)
  File "/Users/colin/code/recidiviz-data/recidiviz/common/str_field_utils.py", line 350, in parse_date
    parsed = parse_datetime(date_string, from_dt=from_dt)
  File "/Users/colin/code/recidiviz-data/recidiviz/common/str_field_utils.py", line 270, in parse_datetime
    raise ValueError(f"cannot parse date: {date_string}")
ValueError: cannot parse date: 2013-02-30
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

N/A

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- ~Tests have been written to cover the code changed/added as part of
this pull request~

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no
"Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: bd0d8fc7cc175c36a7c32dc810669c565912c4ec