[Tools] Enforce input_columns types in run_mappings_against_ingest_view_results (Recidiviz/recidiviz-data#44428)
## Description of the change
We have a unittest that checks that the `input_columns` schema matches
the view output schema but some people's development flow starts with
`run_mappings_against_ingest_view_results` +
`run_sandbox_ingest_pipeline`. This adds a check that the YAML schema
matches the actual schema, which will catch certain classes of errors
before running an actual Dataflow pipeline.

Example script run:
```
(recidiviz-data) ageiduschek@Annas-MacBook-Pro-2 recidiviz-data %     python -m recidiviz.tools.ingest.development.run_mappings_against_ingest_view_results \
        --project-id recidiviz-staging \
        --state-code US_IA \
        --ingest-view-name supervision_periods
Running `supervision_periods` view query against latest raw data tables...
Query completed.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/ageiduschek/src/recidiviz-data/recidiviz/tools/ingest/development/run_mappings_against_ingest_view_results.py", line 295, in <module>
    main(
  File "/Users/ageiduschek/src/recidiviz-data/recidiviz/tools/ingest/development/run_mappings_against_ingest_view_results.py", line 242, in main
    validate_ingest_view_output_schema(
  File "/Users/ageiduschek/src/recidiviz-data/recidiviz/tools/ingest/development/run_mappings_against_ingest_view_results.py", line 227, in validate_ingest_view_output_schema
    raise ValueError(
ValueError: Found query result schema which does not match the schema defined in the input_columns in the YAML mapping file.
  Columns in query results but missing from YAML input_columns: []
  Columns in YAML input_columns but not query results: []
  Columns with mismatched types in query results and YAML input_columns: ['end_date', 'start_date']
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

See https://recidiviz.slack.com/archives/C01J3JV7962/p1749847429076079

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 5b5bd344cc45acbaf5409bfa2730ef38342eaa6d