[ingest scripts] Make run_mappings script proceed after exceptions (Recidiviz/recidiviz-data#32869)
## Description of the change

When I run this script locally and it finds a value in ingest view
results that I have not mapped for the view I'm testing, the script
crashes rather than printing the error, saving the stack trace to the
errors file, and then proceeding. Here is an example of the output when
this happens:

```
Error: Could not parse Class 1 Date Adjustment when building <enum 'StateIncarcerationPeriodAdmissionReason'>
Traceback (most recent call last):
  File "/Users/elisegonzalez/Recidiviz/recidiviz-data/recidiviz/ingest/direct/ingest_mappings/ingest_view_manifest_compiler.py", line 97, in parse_contents
    output_tree = self.output.build_from_row(row, context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elisegonzalez/Recidiviz/recidiviz-data/recidiviz/ingest/direct/ingest_mappings/ingest_view_manifest.py", line 225, in build_from_row
    field_value = field_manifest.build_from_row(row, context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elisegonzalez/Recidiviz/recidiviz-data/recidiviz/ingest/direct/ingest_mappings/ingest_view_manifest.py", line 669, in build_from_row
    child_entity = child_manifest.build_from_row(row, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elisegonzalez/Recidiviz/recidiviz-data/recidiviz/ingest/direct/ingest_mappings/ingest_view_manifest.py", line 225, in build_from_row
    field_value = field_manifest.build_from_row(row, context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elisegonzalez/Recidiviz/recidiviz-data/recidiviz/ingest/direct/ingest_mappings/ingest_view_manifest.py", line 902, in build_from_row
    return self.enum_parser.parse(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elisegonzalez/Recidiviz/recidiviz-data/recidiviz/common/constants/enum_parser.py", line 121, in parse
    raise EnumParsingError(self.enum_cls, raw_text)
recidiviz.common.constants.enum_parser.EnumParsingError: Could not parse Class 1 Date Adjustment when building <enum 'StateIncarcerationPeriodAdmissionReason'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/elisegonzalez/Recidiviz/recidiviz-data/recidiviz/tools/ingest/development/run_mappings_against_ingest_view_results.py", line 244, in <module>
    main(
  File "/Users/elisegonzalez/Recidiviz/recidiviz-data/recidiviz/tools/ingest/development/run_mappings_against_ingest_view_results.py", line 195, in main
    parse_results(region, ingest_view_name, contents_handle, write_results)
  File "/Users/elisegonzalez/Recidiviz/recidiviz-data/recidiviz/tools/ingest/development/run_mappings_against_ingest_view_results.py", line 170, in parse_results
    ).parse_contents(
      ^^^^^^^^^^^^^^^
  File "/Users/elisegonzalez/Recidiviz/recidiviz-data/recidiviz/ingest/direct/ingest_mappings/ingest_view_manifest_compiler.py", line 100, in parse_contents
    result_callable(i, row, e)
  File "/Users/elisegonzalez/Recidiviz/recidiviz-data/recidiviz/tools/ingest/development/run_mappings_against_ingest_view_results.py", line 159, in result_processor
    traceback.print_exception(
  File "/Users/elisegonzalez/.pyenv/versions/3.11.6/lib/python3.11/traceback.py", line 123, in print_exception
    value, tb = _parse_value_tb(exc, value, tb)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/elisegonzalez/.pyenv/versions/3.11.6/lib/python3.11/traceback.py", line 98, in _parse_value_tb
    raise ValueError("Both or neither of value and tb must be given")
ValueError: Both or neither of value and tb must be given
```
The first exception is the one that I would expect to be logged in the
errors file. The second one seems to be a problem with the call to
actually print the first exception into the errors file. I tweaked the
call to `traceback.print_exception` so that this script doesn't crash
every time it finds a problem. I'm curious if this works for people who
don't have this issue with the script as it is now?

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 9f8b9da460a0ccde817fe7979f75615d23e70bd7