[bug] update location of big query constants to not get pulled in by cloud functions (Recidiviz/recidiviz-data#30691)
## Description of the change

unblocks deploy (logs below) by moving `bigquery` import out of
`direct_ingest_constants`. should more seriously consider rewriting the
cloud function to use `storage` library directory or Recidiviz/recidiviz-data#6861 to avoid this
more permanently

```

2024-06-14 16:25:59.304 EDT
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-06-14 16:25:59.304 EDT
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-06-14 16:25:59.304 EDT
  File "/workspace/recidiviz/cloud_functions/ingest_filename_normalization.py", line 35, in <module>
2024-06-14 16:25:59.304 EDT
    from recidiviz.ingest.direct.gcs.direct_ingest_gcs_file_system import (
2024-06-14 16:25:59.304 EDT
  File "/workspace/recidiviz/ingest/direct/gcs/direct_ingest_gcs_file_system.py", line 42, in <module>
2024-06-14 16:25:59.304 EDT
    from recidiviz.ingest.direct.types.direct_ingest_constants import (
2024-06-14 16:25:59.304 EDT
  File "/workspace/recidiviz/ingest/direct/types/direct_ingest_constants.py", line 19, in <module>
2024-06-14 16:25:59.304 EDT
    from google.cloud.bigquery import SchemaField
2024-06-14 16:26:00.277 EDT
Container called exit(1).
2024-06-14 16:26:00.278 EDT
ModuleNotFoundError: No module named 'google.cloud.bigquery'
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 3347f7a64f22d7ba41f035d5dfd4bfa4c9195305