[us_tn] add `update_history` to a few configs (Recidiviz/recidiviz-data#34842)
## Description of the change

adds `update_history` to `TDPOP` and
`RECIDIVIZ_REFERENCE_staff_supervisor_and_caseload_roster` to fix the
following errors during new raw data infra re-import:

```
recidiviz-staging-direct-ingest-state-us-tn-secondary/unprocessed_2022-02-21T00:00:00:000000_raw_TDPOP.csv: Columns [Offense_Date, SID_Date] found in config for [TDPOP] were not found in the raw data file.
Traceback (most recent call last):
  File "/home/airflow/gcs/dags/recidiviz/airflow/dags/raw_data/gcs_file_processing_tasks.py", line 527, in read_and_verify_column_headers_concurrently
    results[file_path.abs_path()] = future.result()
                                    ^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/python3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/airflow/dags/raw_data/gcs_file_processing_tasks.py", line 501, in _read_and_validate_headers
    return file_reader.read_and_validate_column_headers(gcs_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/ingest/direct/raw_data/read_raw_file_column_headers.py", line 70, in read_and_validate_column_headers
    return self._normalize_and_validate_column_headers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/ingest/direct/raw_data/read_raw_file_column_headers.py", line 176, in _normalize_and_validate_column_headers
    raise ValueError(
ValueError: Columns [Offense_Date, SID_Date] found in config for [TDPOP] were not found in the raw data file.
```
```
recidiviz-staging-direct-ingest-state-us-tn-secondary/unprocessed_2023-10-24T00:00:00:000000_raw_RECIDIVIZ_REFERENCE_staff_supervisor_and_caseload_roster.csv: Columns [SupervisorEmail, first_name, UpdatedRoleType, SpecializedTeam] found in config for [RECIDIVIZ_REFERENCE_staff_supervisor_and_caseload_roster] were not found in the raw data file.
Traceback (most recent call last):
  File "/home/airflow/gcs/dags/recidiviz/airflow/dags/raw_data/gcs_file_processing_tasks.py", line 527, in read_and_verify_column_headers_concurrently
    results[file_path.abs_path()] = future.result()
                                    ^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/python3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/airflow/dags/raw_data/gcs_file_processing_tasks.py", line 501, in _read_and_validate_headers
    return file_reader.read_and_validate_column_headers(gcs_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/ingest/direct/raw_data/read_raw_file_column_headers.py", line 70, in read_and_validate_column_headers
    return self._normalize_and_validate_column_headers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/ingest/direct/raw_data/read_raw_file_column_headers.py", line 176, in _normalize_and_validate_column_headers
    raise ValueError(
ValueError: Columns [SupervisorEmail, first_name, UpdatedRoleType, SpecializedTeam] found in config for [RECIDIVIZ_REFERENCE_staff_supervisor_and_caseload_roster] were not found in the raw data file.
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Part of Recidiviz/recidiviz-data#34590

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 690d65959f62b1483dc3a283ed42128b0b2bc254