[Bug] Enforce ORDER BY usage in ingest views (Recidiviz/recidiviz-data#32219)
## Description of the change

@lydiamasri2 found that our ingest view builder was erroneously blocking
an ORDER BY in a QUALIFY statement if it was at the end of a query:
https://recidiviz.slack.com/archives/C01J3JV7962/p1723129530644379

This PR corrects that error and makes our ORDER BY check more strict
using sqlglot. There are three discrete changes (three commits)

1. Make the new check using sqlglot and consolidate our sqlglot code for
tests. The tests fail here because we had some ingest views using ORDER
BY in CTEs!
2. Removed the extra ORDER BY statements from ingest views. The tests
pass with no changes to ingest fixtures!
3. Removed the old ORDER BY check

The error message is similar to the old one, but now includes the clause
directly. For example:
```
ValueError: Found ORDER BY statement that isn't applied to window or aggregation: 'ORDER BY OffenderQuestionnaireTemplateId, SectionId' in ingest view 'supervision_violation_supplemental'
```

I'm also happy to wait on
https://github.com/Recidiviz/recidiviz-data/pull/32071 being merged in
and can update that ingest view to be extra sure.

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| **Type: Bug** | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes
[Recidiviz/recidiviz-data#32198](https://github.com/Recidiviz/recidiviz-data/issues/32198)

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 4bf475dd4d860560dff50675375ed0e1e4d002b5