[Pipfile] Pin paramiko and sshtunnel versions (Recidiviz/recidiviz-data#46132)
## Description of the change

NE raw data export job is failing with
```
2025-08-08 00:01:47.350 PDT
File "/app/.venv/lib/python3.11/site-packages/sshtunnel.py", line 1093, in get_keys
2025-08-08 00:01:47.350 PDT
'dsa': paramiko.DSSKey,
2025-08-08 00:01:47.350 PDT
^^^^^^^^^^^^^^^
2025-08-08 00:01:47.486 PDT
Container called exit(1).
2025-08-08 00:01:47.487 PDT
AttributeError: module 'paramiko' has no attribute 'DSSKey'. Did you mean: 'RSAKey'?
```
paramiko's latest [release](https://www.paramiko.org/changelog.html)
deprecated `DSSKey`. someone is working on fixing it in
[sshtunnel](https://github.com/pahaz/sshtunnel/pull/300) so we can pin
to previous paramiko version until that's fixed

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Recidiviz/recidiviz-data#46131

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: eaf192c7cf3e469dcf82f37ec66d7f8eb5f44690