[Bugfix][CNI] Include all CNI config files in Cloud Composer (Recidiviz/recidiviz-data#94043)
## Description of the change

Some refactoring I did last week made it so that the LLM extraction
config objects are getting read / parsed as part of document store code.
When I went to run the document store DAG, it crashed with this stack:

```
  File "/home/airflow/gcs/dags/recidiviz/airflow/dags/llm_document_extraction/document_store_tasks.py", line 73, in run_document_discovery
    collection_result = discoverer.run()
                        ^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/documents/store/new_document_discovery.py", line 100, in run
    self.config.temp_document_metadata_updates_table_address(
    ^^^^^^^^^^^
  File "<attrs generated getattr recidiviz.documents.store.new_document_discovery.NewDocumentDiscoverer>", line 6, in __getattr__
    result = func(self)
             ^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/documents/store/new_document_discovery.py", line 75, in config
    return get_document_collection_config(self.state_code, self.collection_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/documents/store/document_collection_config_collectors.py", line 95, in get_document_collection_config
    configs = collect_all_document_collection_configs(state_code, config_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/documents/store/document_collection_config_collectors.py", line 69, in collect_all_document_collection_configs
    all_first_order_extractor_configs = load_first_order_llm_extractor_configs(module)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/documents/extraction/llm_extractor_config_collectors.py", line 94, in load_first_order_llm_extractor_configs
    model_registry = load_llm_model_registry(module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/documents/extraction/models/llm_model_registry.py", line 739, in load_llm_model_registry
    return LLMModelRegistry.from_yaml(model_registry_yaml_path(config_module))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/documents/extraction/models/llm_model_registry.py", line 678, in from_yaml
    registry_dict = YAMLDict.from_path(yaml_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/gcs/dags/recidiviz/utils/yaml_dict.py", line 57, in from_path
    with open(yaml_path, encoding="utf-8") as yaml_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/gcs/dags/recidiviz/documents/config/model_registry.yaml'
```

This PR updates the cloud composer configuration so that we now upload
ALL of the CNI-relevant config files.

Confirmed this actually worked by running the following from my branch
and re-triggering the DAG:

```
mkdir -p /tmp/airflow_source_files

uv run python -m recidiviz.tools.airflow.get_airflow_source_files \
    --output-path /tmp/airflow_source_files \
    --dry-run False

gcloud storage rsync /tmp/airflow_source_files \
  gs://us-central1-orchestration-v-39056c2e-bucket/dags \
  --recursive \
  --checksums-only \
  --delete-unmatched-destination-objects \
  --exclude='airflow_monitoring\.py'
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### ⚠️ Changing an opportunity record?
Please [consult this
document](https://www.notion.so/recidiviz/How-to-make-a-change-to-the-Opportunity-Record-1d67889f4d19807f8109f9f2f007dde3)
first to see if additional changes might be required in the admin panel
or a Zod schema. You can confirm with Polaris if unsure.

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 615b21414b7b37cdc0f1367b528cf35cba154e88