Revert "[Justice Counts] changed pool_recycle to -1 for JC (Recidiviz/recidiviz-data#20000)" (Recidiviz/recidiviz-data#20379)
## Description of the change

In Recidiviz/recidiviz-data#20000 we tried getting rid of our pool_recycle parameter to avoid
seeing messages like

![230427596-1facc2e0-bee4-4051-904a-bc8c1a47fc15](https://user-images.githubusercontent.com/99899591/233451684-7263cb09-2e81-404d-b55a-e6a4089cdfe5.png)

However, we are now running into the following errors (e.g.
[here](https://recidiviz-inc.sentry.io/issues/4085952129/?project=4504532096516096&query=is%3Aignored&referrer=issue-stream&stream_index=0)
in Sentry):

```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

which is the reason why other folks set the pool_recycle parameter to
600 in the first place (see
https://github.com/Recidiviz/recidiviz-data/pull/3818 for context). We
thought maybe this wouldn't happen because the reasoning in that PR
seemed to apply to Compute Engine, but it seems we're not exempt.

Reverting to how it was previously!

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no
"Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 89eeacdbe7aeeaf0b143e2bc92e23f9c57b74c5c