[Deploy] Python 3.11 includes a builtin `tomllib` package, use it (Recidiviz/recidiviz-data#26359)
## Description of the change
`tomli` was never listed as an explicit dependency in our Pipfile. Now
that Python 3.11 has `tomllib` as a builtin package, whichever package
was providing us with this dependency has since dropped it.

Updates our only usage of it to use `tomllib`.

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

```
Performing pre-deploy verification
>  Checking script is executing in a pipenv shell
>  Checking Python is correct version
>  >  Traceback (most recent call last):
>  >    File "<stdin>", line 1, in <module>
>  >  ModuleNotFoundError: No module named 'tomli'
>  >  Failed with exit code 1
>  Failed with exit code 1
```
## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: aad8b7c4a5fcb1b9d1a6362d7ea446ddd1328b12