Update Uniqueness Constraint to be Partial in Raw File Metadata Table (Recidiviz/recidiviz-data#17821)
## Description of the change

While conducting testing for secondary raw data import, I copied
previously seen (but since invalidated) raw files back into the
secondary ingest bucket (this is a flow that is expected, as IEs will
eventually be using the `copy` and `move` scripts to re-ingest files in
secondary raw data import). When I did so, the following error was
raised:

```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "one_normalized_name_per_region_and_instance"
DETAIL:  Key (region_code, raw_data_instance, normalized_file_name)=(US_OZ, SECONDARY, unprocessed_2023-01-11T00:00:00:000000_raw_gloFS_person.csv) already exists.
```

We should have this constraint only be for _non-invalidated_ files, not
all files. There will very likely be SEVERAL copies of the _invalidated_
files.

Inspiration for how to do partial unique constraints comes from this
[Stack Overflow
post](https://stackoverflow.com/questions/27976683/creating-partial-unique-index-with-sqlalchemy-on-postgres).

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Recidiviz/recidiviz-data#17683

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] This pull request has been moved out of a Draft state, has no
"Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 0ef3062653c2069efc173746b62d5765d5f2ac7c