[Bug] Add secret replication location (Recidiviz/recidiviz-data#92124)
## Description of the change

Seeing a TF apply error regarding a missing replication location for a
new secret. Added.

```
Error: Error creating Secret: googleapi: Error 400: Constraint constraints/gcp.resourceLocations violated for [orgpolicy:projects/984160736970] attempting to create a secret in [global]. For more information, see https://cloud.google.com/resource-manager/docs/organization-policy/defining-locations.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
    "violations": [
      {
        "description": "Constraint constraints/gcp.resourceLocations violated for [orgpolicy:projects/984160736970] attempting to create a secret in [global]. For more information, see https://cloud.google.com/resource-manager/docs/organization-policy/defining-locations.",
        "subject": "orgpolicy:projects/984160736970",
        "type": "constraints/gcp.resourceLocations"
      }
    ]
  }
]

  with google_secret_manager_secret.typesense_backfill_function_url,
  on cloud-run.tf line 292, in resource "google_secret_manager_secret" "typesense_backfill_function_url":
 292: resource "google_secret_manager_secret" "typesense_backfill_function_url" {
```

I was not able to run TF plan locally since the recent staging deploy TF
apply failed, but hopefully the CI check will be successful.
```(recidiviz)  recidiviz-data (jovergaag/secret-location-fix)$ ./recidiviz/tools/deploy/terraform_plan.sh recidiviz-staging
##### Running for project recidiviz-staging ########
[2026-07-17 13:42:38] Running: git fetch --all --tags --prune --prune-tags --force
Getting last deployed version tag from Terraform state for project recidiviz-staging...
Retrieved last deployed version: v1.690.0
[./recidiviz/tools/deploy/terraform_plan.sh:39] Most recent version tag on this branch [v1.690.0-alpha.2] does not
[./recidiviz/tools/deploy/terraform_plan.sh:40] match last deployed version tag [v1.690.0] in
[./recidiviz/tools/deploy/terraform_plan.sh:41] project [recidiviz-staging]. Make sure you have rebased on the latest
[./recidiviz/tools/deploy/terraform_plan.sh:42] version of the released branch.
[2026-07-17 13:42:41] Running: exit 1
Failed with exit code 1
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes #XXXX

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [ ] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [ ] Tests have been written to cover the code changed/added as part of
this pull request

### ⚠️ Changing an opportunity record?
Please [consult this
document](https://www.notion.so/recidiviz/How-to-make-a-change-to-the-Opportunity-Record-1d67889f4d19807f8109f9f2f007dde3)
first to see if additional changes might be required in the admin panel
or a Zod schema. You can confirm with Polaris if unsure.

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: bdbeab5f30021cc2ffa27184bf2d9d5ddc190a60