[alerting] Alert on `non_blocking_failure_message` (Recidiviz/recidiviz-data#79839)
## Description of the change

treat file with `non_blocking_failure_message` as a failure so we alert.

an example alert title and text
```
[production][US_TN] US_TN.PhotoIDRequest, started: 2026-05-17 09:02 UTC Recidiviz/recidiviz-data#79475

Failed run of [US_TN.PhotoIDRequest] on the following dates: [ 2026-05-17T09:02:56.410851+00:00 ].

Most recent error message:
========================================================================================================================
============================================== NON-BLOCKING FAILURES (1) ===============================================
========================================================================================================================
[PhotoIDRequest] with update_datetime [2026-05-17T08:05:08.005212+00:00] and file_id [1705835] failed:
1 pre-import validation(s) failed for file [PhotoIDRequest]. If you wish [PhotoIDRequest] to be permanently excluded from any validation,  please add the validation_type and exemption_reason to pre_import_validation_exemptions for a table-wide exemption or to pre_import_column_validation_exemptions for a column-specific exemption in the raw file config.
**Non-blocking failure**
This failure does not block the file import but should be reviewed and addressed.
Error: unknown known_values found in column foo
Validation type: KNOWN_VALUES
Validation query: SELECT ....
========================================================================================================================
....
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Recidiviz/recidiviz-data#71014

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### ⚠️ Changing an opportunity record?
Please [consult this
document](https://www.notion.so/recidiviz/How-to-make-a-change-to-the-Opportunity-Record-1d67889f4d19807f8109f9f2f007dde3)
first to see if additional changes might be required in the admin panel
or a Zod schema. You can confirm with Polaris if unsure.

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful
to a reviewer
- [ ] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: 763dd7914830518fbf20c88f6bd3de1f98e288c9