[raw data] script for backfilling metadata db (Recidiviz/recidiviz-data#35616)
## Description of the change

adds a script for backfilling new raw data infra metadata tables using
the legacy raw data metadata table.

randomly also realized that the legacy `DirectIngestRawFileMetadata`
object didnt have `is_invalidated` on the `entities.py` obj?

sample outputs
(for `US_ID` w/ id conflicts)
```
(recidiviz-data) recidiviz-data(ethanoro/backfill-db*)$ python -m recidiviz.tools.ingest.one_offs.backfill_new_raw_data_infra_from_legacy \
    --project-id recidiviz-staging \
    --state-code US_ID \
    --raw-data-instance PRIMARY \
    --dry-run True
Starting Cloud SQL Proxy container for recidiviz-staging:us-east1:dev-operations-data-0x17a1b...
Started Cloud SQL Proxy container with name: serene_nightingale
If you encounter issues with connecting, check the logs `docker logs serene_nightingale`
Killing Cloud SQL Proxy container on :5440 with name: serene_nightingale
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/oro/recidiviz/recidiviz-data/recidiviz/tools/ingest/one_offs/backfill_new_raw_data_infra_from_legacy.py", line 252, in <module>
    manager.backfill(dry_run=args.dry_run)
  File "/Users/oro/recidiviz/recidiviz-data/recidiviz/tools/ingest/one_offs/backfill_new_raw_data_infra_from_legacy.py", line 190, in backfill
    self.ensure_no_conflicting_ids(session=session)
  File "/Users/oro/recidiviz/recidiviz-data/recidiviz/tools/ingest/one_offs/backfill_new_raw_data_infra_from_legacy.py", line 109, in ensure_no_conflicting_ids
    raise ValueError(f"Found [{len(conflicting_ids)}] conflicting ids")
ValueError: Found [6305] conflicting ids
```

for `US_IX`, no conflcits
```
(recidiviz-data) recidiviz-data(ethanoro/backfill-db*)$ python -m recidiviz.tools.ingest.one_offs.backfill_new_raw_data_infra_from_legacy \
    --project-id recidiviz-staging \
    --state-code US_IX \
    --raw-data-instance PRIMARY \
    --dry-run True
Starting Cloud SQL Proxy container for recidiviz-staging:us-east1:dev-operations-data-0x17a1b...
Started Cloud SQL Proxy container with name: strange_einstein
If you encounter issues with connecting, check the logs `docker logs strange_einstein`
Found no conflicting ids; proceeding...
Found the following rows to copy over:
 	-hsn_BedStatus: 558
	-ref_Employer_Address: 555
	   .....									    .....
	< ..... a BUNCH of other tags ..... >
	   .....										.....
	-scl_Detainer: 555
	-scl_ProbationSupervision: 555
Proceed with backfill? [dry run mode: True] [y/n]:
y
Dry run, skipping backfill
Killing Cloud SQL Proxy container on :5440 with name: strange_einstein
```

## Type of change

> All pull requests must have at least one of the following labels
applied (otherwise the PR will fail):

| Label | Description |
|-----------------------------
|-----------------------------------------------------------------------------------------------------------
|
| Type: Bug | non-breaking change that fixes an issue |
| Type: Feature | non-breaking change that adds functionality |
| Type: Breaking Change | fix or feature that would cause existing
functionality to not work as expected |
| Type: Non-breaking refactor | change addresses some tech debt item or
prepares for a later change, but does not change functionality |
| Type: Configuration Change | adjusts configuration to achieve some end
related to functionality, development, performance, or security |
| Type: Dependency Upgrade | upgrades a project dependency - these
changes are not included in release notes |

## Related issues

Closes Recidiviz/recidiviz-data#35566

## Checklists

### Development

**This box MUST be checked by the submitter prior to merging**:
- [x] **Double- and triple-checked that there is no Personally
Identifiable Information (PII) being mistakenly added in this pull
request**

These boxes should be checked by the submitter prior to merging:
- [x] Tests have been written to cover the code changed/added as part of
this pull request

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful
to a reviewer
- [x] Potential security implications or infrastructural changes have
been considered, if relevant

GitOrigin-RevId: d61ed2d920a04cab9c588e44e272454285431443